//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

#[cfg(feature = "objc2")]
extern_class!(
    /// This class represents a folder on an ICCameraDevice object.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/iccamerafolder?language=objc)
    #[unsafe(super(ICCameraItem, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
    pub struct ICCameraFolder;
);

#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
unsafe impl NSObjectProtocol for ICCameraFolder {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
    unsafe impl ICCameraFolder {
        /// ￼A list of items contained by this folder.
        #[method_id(@__retain_semantics Other contents)]
        pub unsafe fn contents(&self) -> Option<Retained<NSArray<ICCameraItem>>>;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
    unsafe impl ICCameraFolder {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
