//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "ICCameraItem")]
    pub struct ICCameraFile;

    #[cfg(feature = "ICCameraItem")]
    unsafe impl ClassType for ICCameraFile {
        #[inherits(NSObject)]
        type Super = ICCameraItem;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "ICCameraItem")]
unsafe impl NSObjectProtocol for ICCameraFile {}

extern_methods!(
    #[cfg(feature = "ICCameraItem")]
    unsafe impl ICCameraFile {
        #[method(width)]
        pub unsafe fn width(&self) -> NSInteger;

        #[method(height)]
        pub unsafe fn height(&self) -> NSInteger;

        #[method_id(@__retain_semantics Other originalFilename)]
        pub unsafe fn originalFilename(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other createdFilename)]
        pub unsafe fn createdFilename(&self) -> Option<Retained<NSString>>;

        #[cfg(feature = "libc")]
        #[method(fileSize)]
        pub unsafe fn fileSize(&self) -> libc::off_t;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(orientation)]
        pub unsafe fn orientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(setOrientation:)]
        pub unsafe fn setOrientation(&self, orientation: ICEXIFOrientationType);

        #[method(duration)]
        pub unsafe fn duration(&self) -> c_double;

        #[method(highFramerate)]
        pub unsafe fn highFramerate(&self) -> bool;

        #[method(timeLapse)]
        pub unsafe fn timeLapse(&self) -> bool;

        #[method(firstPicked)]
        pub unsafe fn firstPicked(&self) -> bool;

        #[method_id(@__retain_semantics Other originatingAssetID)]
        pub unsafe fn originatingAssetID(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other groupUUID)]
        pub unsafe fn groupUUID(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other gpsString)]
        pub unsafe fn gpsString(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other relatedUUID)]
        pub unsafe fn relatedUUID(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other burstUUID)]
        pub unsafe fn burstUUID(&self) -> Option<Retained<NSString>>;

        #[method(burstFavorite)]
        pub unsafe fn burstFavorite(&self) -> bool;

        #[method(burstPicked)]
        pub unsafe fn burstPicked(&self) -> bool;

        #[method_id(@__retain_semantics Other sidecarFiles)]
        pub unsafe fn sidecarFiles(&self) -> Option<Retained<NSArray<ICCameraItem>>>;

        #[method_id(@__retain_semantics Other pairedRawImage)]
        pub unsafe fn pairedRawImage(&self) -> Option<Retained<ICCameraFile>>;

        #[method_id(@__retain_semantics Other fileCreationDate)]
        pub unsafe fn fileCreationDate(&self) -> Option<Retained<NSDate>>;

        #[method_id(@__retain_semantics Other fileModificationDate)]
        pub unsafe fn fileModificationDate(&self) -> Option<Retained<NSDate>>;

        #[method_id(@__retain_semantics Other exifCreationDate)]
        pub unsafe fn exifCreationDate(&self) -> Option<Retained<NSDate>>;

        #[method_id(@__retain_semantics Other exifModificationDate)]
        pub unsafe fn exifModificationDate(&self) -> Option<Retained<NSDate>>;

        #[cfg(feature = "block2")]
        #[method(requestThumbnailDataWithOptions:completion:)]
        pub unsafe fn requestThumbnailDataWithOptions_completion(
            &self,
            options: Option<&NSDictionary<ICCameraItemThumbnailOption, AnyObject>>,
            completion: &block2::Block<dyn Fn(*mut NSData, *mut NSError)>,
        );

        #[cfg(feature = "block2")]
        #[method(requestMetadataDictionaryWithOptions:completion:)]
        pub unsafe fn requestMetadataDictionaryWithOptions_completion(
            &self,
            options: Option<&NSDictionary<ICCameraItemMetadataOption, AnyObject>>,
            completion: &block2::Block<dyn Fn(*mut NSDictionary, *mut NSError)>,
        );

        #[cfg(feature = "block2")]
        #[method_id(@__retain_semantics Other requestDownloadWithOptions:completion:)]
        pub unsafe fn requestDownloadWithOptions_completion(
            &self,
            options: Option<&NSDictionary<ICDownloadOption, AnyObject>>,
            completion: &block2::Block<dyn Fn(*mut NSString, *mut NSError)>,
        ) -> Option<Retained<NSProgress>>;

        #[cfg(all(feature = "block2", feature = "libc"))]
        #[method(requestReadDataAtOffset:length:completion:)]
        pub unsafe fn requestReadDataAtOffset_length_completion(
            &self,
            offset: libc::off_t,
            length: libc::off_t,
            completion: &block2::Block<dyn Fn(*mut NSData, *mut NSError)>,
        );

        #[cfg(feature = "block2")]
        #[method(requestSecurityScopedURLWithCompletion:)]
        pub unsafe fn requestSecurityScopedURLWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(*mut NSURL, *mut NSError)>,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "ICCameraItem")]
    unsafe impl ICCameraFile {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
