//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_TYPED_ENUM
pub type ICCameraItemMetadataOption = NSString;

// NS_TYPED_ENUM
pub type ICCameraItemThumbnailOption = NSString;

extern "C" {
    pub static ICImageSourceThumbnailMaxPixelSize: &'static ICCameraItemThumbnailOption;
}

extern "C" {
    pub static ICImageSourceShouldCache: &'static ICCameraItemThumbnailOption;
}

// NS_TYPED_ENUM
pub type ICDownloadOption = NSString;

extern "C" {
    pub static ICDownloadsDirectoryURL: &'static ICDownloadOption;
}

extern "C" {
    pub static ICSaveAsFilename: &'static ICDownloadOption;
}

extern "C" {
    pub static ICSavedFilename: &'static ICDownloadOption;
}

extern "C" {
    pub static ICSavedAncillaryFiles: &'static ICDownloadOption;
}

extern "C" {
    pub static ICOverwrite: &'static ICDownloadOption;
}

extern "C" {
    pub static ICDeleteAfterSuccessfulDownload: &'static ICDownloadOption;
}

extern "C" {
    pub static ICDownloadSidecarFiles: &'static ICDownloadOption;
}

extern "C" {
    pub static ICTruncateAfterSuccessfulDownload: &'static ICDownloadOption;
}

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICCameraItem;

    unsafe impl ClassType for ICCameraItem {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICCameraItem {}

extern_methods!(
    unsafe impl ICCameraItem {
        #[cfg(all(feature = "ICCameraDevice", feature = "ICDevice"))]
        #[method_id(@__retain_semantics Other device)]
        pub unsafe fn device(&self) -> Option<Retained<ICCameraDevice>>;

        #[cfg(feature = "ICCameraFolder")]
        #[method_id(@__retain_semantics Other parentFolder)]
        pub unsafe fn parentFolder(&self) -> Option<Retained<ICCameraFolder>>;

        #[method_id(@__retain_semantics Other name)]
        pub unsafe fn name(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other UTI)]
        pub unsafe fn UTI(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other fileSystemPath)]
        pub unsafe fn fileSystemPath(&self) -> Option<Retained<NSString>>;

        #[method(isLocked)]
        pub unsafe fn isLocked(&self) -> bool;

        #[method(isRaw)]
        pub unsafe fn isRaw(&self) -> bool;

        #[method(isInTemporaryStore)]
        pub unsafe fn isInTemporaryStore(&self) -> bool;

        #[method_id(@__retain_semantics Other creationDate)]
        pub unsafe fn creationDate(&self) -> Option<Retained<NSDate>>;

        #[method_id(@__retain_semantics Other modificationDate)]
        pub unsafe fn modificationDate(&self) -> Option<Retained<NSDate>>;

        #[method_id(@__retain_semantics Other metadata)]
        pub unsafe fn metadata(&self) -> Option<Retained<NSDictionary>>;

        #[method_id(@__retain_semantics Other userData)]
        pub unsafe fn userData(&self) -> Option<Retained<NSMutableDictionary>>;

        #[method(ptpObjectHandle)]
        pub unsafe fn ptpObjectHandle(&self) -> c_uint;

        #[method(wasAddedAfterContentCatalogCompleted)]
        pub unsafe fn wasAddedAfterContentCatalogCompleted(&self) -> bool;

        #[method(requestThumbnail)]
        pub unsafe fn requestThumbnail(&self);

        #[method(requestMetadata)]
        pub unsafe fn requestMetadata(&self);

        #[method(flushThumbnailCache)]
        pub unsafe fn flushThumbnailCache(&self);

        #[method(flushMetadataCache)]
        pub unsafe fn flushMetadataCache(&self);

        #[deprecated]
        #[method_id(@__retain_semantics Other metadataIfAvailable)]
        pub unsafe fn metadataIfAvailable(
            &self,
        ) -> Option<Retained<NSDictionary<NSString, AnyObject>>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICCameraItem {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
