//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "ICCameraItem")]
    pub struct ICCameraFolder;

    #[cfg(feature = "ICCameraItem")]
    unsafe impl ClassType for ICCameraFolder {
        #[inherits(NSObject)]
        type Super = ICCameraItem;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "ICCameraItem")]
unsafe impl NSObjectProtocol for ICCameraFolder {}

extern_methods!(
    #[cfg(feature = "ICCameraItem")]
    unsafe impl ICCameraFolder {
        #[method_id(@__retain_semantics Other contents)]
        pub unsafe fn contents(&self) -> Option<Retained<NSArray<ICCameraItem>>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "ICCameraItem")]
    unsafe impl ICCameraFolder {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
