//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanTakePicture: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanTakePictureUsingShutterReleaseOnCamera: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanDeleteOneFile: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanDeleteAllFiles: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanSyncClock: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanReceiveFile: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceCanAcceptPTPCommands: &'static ICDeviceCapability;
}

extern "C" {
    #[cfg(feature = "ICDevice")]
    pub static ICCameraDeviceSupportsHEIF: &'static ICDeviceCapability;
}

// NS_TYPED_ENUM
pub type ICUploadOption = NSString;

// NS_TYPED_ENUM
pub type ICDeleteResult = NSString;

extern "C" {
    pub static ICDeleteSuccessful: &'static ICDeleteResult;
}

extern "C" {
    pub static ICDeleteCanceled: &'static ICDeleteResult;
}

extern "C" {
    pub static ICDeleteFailed: &'static ICDeleteResult;
}

// NS_TYPED_ENUM
pub type ICDeleteError = NSString;

extern "C" {
    pub static ICDeleteErrorReadOnly: &'static ICDeleteError;
}

extern "C" {
    pub static ICDeleteErrorFileMissing: &'static ICDeleteError;
}

extern "C" {
    pub static ICDeleteErrorDeviceMissing: &'static ICDeleteError;
}

extern "C" {
    pub static ICDeleteErrorCanceled: &'static ICDeleteError;
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICMediaPresentation(pub NSUInteger);
impl ICMediaPresentation {
    #[doc(alias = "ICMediaPresentationConvertedAssets")]
    pub const ConvertedAssets: Self = Self(1);
    #[doc(alias = "ICMediaPresentationOriginalAssets")]
    pub const OriginalAssets: Self = Self(2);
}

unsafe impl Encode for ICMediaPresentation {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICMediaPresentation {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "ICDevice")]
    pub struct ICCameraDevice;

    #[cfg(feature = "ICDevice")]
    unsafe impl ClassType for ICCameraDevice {
        #[inherits(NSObject)]
        type Super = ICDevice;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "ICDevice")]
unsafe impl NSObjectProtocol for ICCameraDevice {}

extern_methods!(
    #[cfg(feature = "ICDevice")]
    unsafe impl ICCameraDevice {
        #[method(contentCatalogPercentCompleted)]
        pub unsafe fn contentCatalogPercentCompleted(&self) -> NSUInteger;

        #[cfg(feature = "ICCameraItem")]
        #[method_id(@__retain_semantics Other contents)]
        pub unsafe fn contents(&self) -> Option<Retained<NSArray<ICCameraItem>>>;

        #[cfg(feature = "ICCameraItem")]
        #[method_id(@__retain_semantics Other mediaFiles)]
        pub unsafe fn mediaFiles(&self) -> Option<Retained<NSArray<ICCameraItem>>>;

        #[method(isEjectable)]
        pub unsafe fn isEjectable(&self) -> bool;

        #[method(isLocked)]
        pub unsafe fn isLocked(&self) -> bool;

        #[method(isAccessRestrictedAppleDevice)]
        pub unsafe fn isAccessRestrictedAppleDevice(&self) -> bool;

        #[method(iCloudPhotosEnabled)]
        pub unsafe fn iCloudPhotosEnabled(&self) -> bool;

        #[method_id(@__retain_semantics Other mountPoint)]
        pub unsafe fn mountPoint(&self) -> Option<Retained<NSString>>;

        #[method(mediaPresentation)]
        pub unsafe fn mediaPresentation(&self) -> ICMediaPresentation;

        #[method(setMediaPresentation:)]
        pub unsafe fn setMediaPresentation(&self, media_presentation: ICMediaPresentation);

        #[method_id(@__retain_semantics Other filesOfType:)]
        pub unsafe fn filesOfType(
            &self,
            file_ut_type: &NSString,
        ) -> Option<Retained<NSArray<NSString>>>;

        #[cfg(all(feature = "ICCameraFile", feature = "ICCameraItem", feature = "libc"))]
        #[method(requestReadDataFromFile:atOffset:length:readDelegate:didReadDataSelector:contextInfo:)]
        pub unsafe fn requestReadDataFromFile_atOffset_length_readDelegate_didReadDataSelector_contextInfo(
            &self,
            file: &ICCameraFile,
            offset: libc::off_t,
            length: libc::off_t,
            read_delegate: &AnyObject,
            selector: Sel,
            context_info: *mut c_void,
        );

        #[cfg(all(feature = "ICCameraFile", feature = "ICCameraItem"))]
        #[method(requestDownloadFile:options:downloadDelegate:didDownloadSelector:contextInfo:)]
        pub unsafe fn requestDownloadFile_options_downloadDelegate_didDownloadSelector_contextInfo(
            &self,
            file: &ICCameraFile,
            options: &NSDictionary<ICDownloadOption, AnyObject>,
            download_delegate: &ProtocolObject<dyn ICCameraDeviceDownloadDelegate>,
            selector: Sel,
            context_info: *mut c_void,
        );

        #[method(cancelDownload)]
        pub unsafe fn cancelDownload(&self);

        #[cfg(feature = "ICCameraItem")]
        #[method(requestDeleteFiles:)]
        pub unsafe fn requestDeleteFiles(&self, files: &NSArray<ICCameraItem>);

        #[cfg(all(feature = "ICCameraItem", feature = "block2"))]
        #[method_id(@__retain_semantics Other requestDeleteFiles:deleteFailed:completion:)]
        pub unsafe fn requestDeleteFiles_deleteFailed_completion(
            &self,
            files: &NSArray<ICCameraItem>,
            delete_failed: &block2::Block<
                dyn Fn(NonNull<NSDictionary<ICDeleteError, ICCameraItem>>),
            >,
            completion: &block2::Block<
                dyn Fn(NonNull<NSDictionary<ICDeleteResult, NSArray<ICCameraItem>>>, *mut NSError),
            >,
        ) -> Option<Retained<NSProgress>>;

        #[method(cancelDelete)]
        pub unsafe fn cancelDelete(&self);

        #[method(requestSyncClock)]
        pub unsafe fn requestSyncClock(&self);

        #[method(timeOffset)]
        pub unsafe fn timeOffset(&self) -> NSTimeInterval;

        #[method(batteryLevelAvailable)]
        pub unsafe fn batteryLevelAvailable(&self) -> bool;

        #[method(batteryLevel)]
        pub unsafe fn batteryLevel(&self) -> NSUInteger;

        #[deprecated = "Sandbox restrictions prohibit writing directly to device hardware"]
        #[method(requestUploadFile:options:uploadDelegate:didUploadSelector:contextInfo:)]
        pub unsafe fn requestUploadFile_options_uploadDelegate_didUploadSelector_contextInfo(
            &self,
            file_url: &NSURL,
            options: &NSDictionary<ICUploadOption, AnyObject>,
            upload_delegate: &AnyObject,
            selector: Sel,
            context_info: *mut c_void,
        );

        #[method(tetheredCaptureEnabled)]
        pub unsafe fn tetheredCaptureEnabled(&self) -> bool;

        #[method(requestTakePicture)]
        pub unsafe fn requestTakePicture(&self);

        #[deprecated = "Third party cameras that support the standard take picture command will have the capability enabled by default. This call will have no effect"]
        #[method(requestEnableTethering)]
        pub unsafe fn requestEnableTethering(&self);

        #[deprecated = "Third party cameras that support the standard take picture command will have the capability enabled by default. This call will have no effect"]
        #[method(requestDisableTethering)]
        pub unsafe fn requestDisableTethering(&self);

        #[cfg(feature = "block2")]
        #[method(ptpEventHandler)]
        pub unsafe fn ptpEventHandler(&self) -> NonNull<block2::Block<dyn Fn(NonNull<NSData>)>>;

        #[cfg(feature = "block2")]
        #[method(setPtpEventHandler:)]
        pub unsafe fn setPtpEventHandler(
            &self,
            ptp_event_handler: &block2::Block<dyn Fn(NonNull<NSData>)>,
        );

        #[method(requestSendPTPCommand:outData:sendCommandDelegate:didSendCommandSelector:contextInfo:)]
        pub unsafe fn requestSendPTPCommand_outData_sendCommandDelegate_didSendCommandSelector_contextInfo(
            &self,
            command: &NSData,
            data: Option<&NSData>,
            send_command_delegate: &AnyObject,
            selector: Sel,
            context_info: *mut c_void,
        );

        #[cfg(feature = "block2")]
        #[method(requestSendPTPCommand:outData:completion:)]
        pub unsafe fn requestSendPTPCommand_outData_completion(
            &self,
            ptp_command: &NSData,
            ptp_data: Option<&NSData>,
            completion: &block2::Block<dyn Fn(NonNull<NSData>, NonNull<NSData>, *mut NSError)>,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "ICDevice")]
    unsafe impl ICCameraDevice {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_protocol!(
    #[cfg(feature = "ICDevice")]
    pub unsafe trait ICCameraDeviceDelegate: ICDeviceDelegate {
        #[cfg(feature = "ICCameraItem")]
        #[method(cameraDevice:didAddItems:)]
        unsafe fn cameraDevice_didAddItems(
            &self,
            camera: &ICCameraDevice,
            items: &NSArray<ICCameraItem>,
        );

        #[cfg(feature = "ICCameraItem")]
        #[method(cameraDevice:didRemoveItems:)]
        unsafe fn cameraDevice_didRemoveItems(
            &self,
            camera: &ICCameraDevice,
            items: &NSArray<ICCameraItem>,
        );

        #[cfg(feature = "ICCameraItem")]
        #[method(cameraDevice:didReceiveMetadata:forItem:error:)]
        unsafe fn cameraDevice_didReceiveMetadata_forItem_error(
            &self,
            camera: &ICCameraDevice,
            metadata: Option<&NSDictionary>,
            item: &ICCameraItem,
            error: Option<&NSError>,
        );

        #[cfg(feature = "ICCameraItem")]
        #[method(cameraDevice:didRenameItems:)]
        unsafe fn cameraDevice_didRenameItems(
            &self,
            camera: &ICCameraDevice,
            items: &NSArray<ICCameraItem>,
        );

        #[method(cameraDeviceDidChangeCapability:)]
        unsafe fn cameraDeviceDidChangeCapability(&self, camera: &ICCameraDevice);

        #[method(cameraDevice:didReceivePTPEvent:)]
        unsafe fn cameraDevice_didReceivePTPEvent(
            &self,
            camera: &ICCameraDevice,
            event_data: &NSData,
        );

        #[method(deviceDidBecomeReadyWithCompleteContentCatalog:)]
        unsafe fn deviceDidBecomeReadyWithCompleteContentCatalog(&self, device: &ICCameraDevice);

        #[method(cameraDeviceDidRemoveAccessRestriction:)]
        unsafe fn cameraDeviceDidRemoveAccessRestriction(&self, device: &ICDevice);

        #[method(cameraDeviceDidEnableAccessRestriction:)]
        unsafe fn cameraDeviceDidEnableAccessRestriction(&self, device: &ICDevice);

        #[cfg(feature = "ICCameraItem")]
        #[optional]
        #[method(cameraDevice:shouldGetThumbnailOfItem:)]
        unsafe fn cameraDevice_shouldGetThumbnailOfItem(
            &self,
            camera_device: &ICCameraDevice,
            item: &ICCameraItem,
        ) -> bool;

        #[cfg(feature = "ICCameraItem")]
        #[optional]
        #[method(cameraDevice:shouldGetMetadataOfItem:)]
        unsafe fn cameraDevice_shouldGetMetadataOfItem(
            &self,
            camera_device: &ICCameraDevice,
            item: &ICCameraItem,
        ) -> bool;

        #[optional]
        #[method(cameraDevice:didCompleteDeleteFilesWithError:)]
        unsafe fn cameraDevice_didCompleteDeleteFilesWithError(
            &self,
            camera: &ICCameraDevice,
            error: Option<&NSError>,
        );

        #[cfg(feature = "ICCameraItem")]
        #[deprecated]
        #[optional]
        #[method(cameraDevice:didAddItem:)]
        unsafe fn cameraDevice_didAddItem(&self, camera: &ICCameraDevice, item: &ICCameraItem);

        #[cfg(feature = "ICCameraItem")]
        #[deprecated]
        #[optional]
        #[method(cameraDevice:didRemoveItem:)]
        unsafe fn cameraDevice_didRemoveItem(&self, camera: &ICCameraDevice, item: &ICCameraItem);

        #[cfg(feature = "ICCameraItem")]
        #[deprecated]
        #[optional]
        #[method(cameraDevice:didReceiveThumbnailForItem:)]
        unsafe fn cameraDevice_didReceiveThumbnailForItem(
            &self,
            camera: &ICCameraDevice,
            item: &ICCameraItem,
        );

        #[cfg(feature = "ICCameraItem")]
        #[deprecated]
        #[optional]
        #[method(cameraDevice:didReceiveMetadataForItem:)]
        unsafe fn cameraDevice_didReceiveMetadataForItem(
            &self,
            camera: &ICCameraDevice,
            item: &ICCameraItem,
        );
    }

    #[cfg(feature = "ICDevice")]
    unsafe impl ProtocolType for dyn ICCameraDeviceDelegate {}
);

extern_protocol!(
    pub unsafe trait ICCameraDeviceDownloadDelegate: NSObjectProtocol {
        #[cfg(all(feature = "ICCameraFile", feature = "ICCameraItem"))]
        #[optional]
        #[method(didDownloadFile:error:options:contextInfo:)]
        unsafe fn didDownloadFile_error_options_contextInfo(
            &self,
            file: &ICCameraFile,
            error: Option<&NSError>,
            options: &NSDictionary<NSString, AnyObject>,
            context_info: *mut c_void,
        );

        #[cfg(all(feature = "ICCameraFile", feature = "ICCameraItem", feature = "libc"))]
        #[optional]
        #[method(didReceiveDownloadProgressForFile:downloadedBytes:maxBytes:)]
        unsafe fn didReceiveDownloadProgressForFile_downloadedBytes_maxBytes(
            &self,
            file: &ICCameraFile,
            downloaded_bytes: libc::off_t,
            max_bytes: libc::off_t,
        );
    }

    unsafe impl ProtocolType for dyn ICCameraDeviceDownloadDelegate {}
);
