//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICDeviceType(pub NSUInteger);
impl ICDeviceType {
    #[doc(alias = "ICDeviceTypeCamera")]
    pub const Camera: Self = Self(0x00000001);
    #[doc(alias = "ICDeviceTypeScanner")]
    pub const Scanner: Self = Self(0x00000002);
}

unsafe impl Encode for ICDeviceType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICDeviceType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICDeviceLocationType(pub NSUInteger);
impl ICDeviceLocationType {
    #[doc(alias = "ICDeviceLocationTypeLocal")]
    pub const Local: Self = Self(0x00000100);
    #[doc(alias = "ICDeviceLocationTypeShared")]
    pub const Shared: Self = Self(0x00000200);
    #[doc(alias = "ICDeviceLocationTypeBonjour")]
    pub const Bonjour: Self = Self(0x00000400);
    #[doc(alias = "ICDeviceLocationTypeBluetooth")]
    pub const Bluetooth: Self = Self(0x00000800);
}

unsafe impl Encode for ICDeviceLocationType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICDeviceLocationType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICDeviceTypeMask(pub NSUInteger);
impl ICDeviceTypeMask {
    #[doc(alias = "ICDeviceTypeMaskCamera")]
    pub const Camera: Self = Self(0x00000001);
    #[doc(alias = "ICDeviceTypeMaskScanner")]
    pub const Scanner: Self = Self(0x00000002);
}

unsafe impl Encode for ICDeviceTypeMask {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICDeviceTypeMask {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICDeviceLocationTypeMask(pub NSUInteger);
impl ICDeviceLocationTypeMask {
    #[doc(alias = "ICDeviceLocationTypeMaskLocal")]
    pub const Local: Self = Self(0x00000100);
    #[doc(alias = "ICDeviceLocationTypeMaskShared")]
    pub const Shared: Self = Self(0x00000200);
    #[doc(alias = "ICDeviceLocationTypeMaskBonjour")]
    pub const Bonjour: Self = Self(0x00000400);
    #[doc(alias = "ICDeviceLocationTypeMaskBluetooth")]
    pub const Bluetooth: Self = Self(0x00000800);
    #[doc(alias = "ICDeviceLocationTypeMaskRemote")]
    pub const Remote: Self = Self(0x0000FE00);
}

unsafe impl Encode for ICDeviceLocationTypeMask {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICDeviceLocationTypeMask {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_TYPED_ENUM
pub type ICDeviceTransport = NSString;

extern "C" {
    pub static ICTransportTypeUSB: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeFireWire: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeBluetooth: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeMassStorage: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeExFAT: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeTCPIP: &'static ICDeviceTransport;
}

extern "C" {
    pub static ICTransportTypeProximity: &'static ICDeviceTransport;
}

// NS_TYPED_ENUM
pub type ICDeviceStatus = NSString;

extern "C" {
    pub static ICStatusNotificationKey: &'static ICDeviceStatus;
}

extern "C" {
    pub static ICStatusCodeKey: &'static ICDeviceStatus;
}

extern "C" {
    pub static ICLocalizedStatusNotificationKey: &'static ICDeviceStatus;
}

// NS_TYPED_ENUM
pub type ICDeviceCapability = NSString;

extern "C" {
    pub static ICDeviceCanEjectOrDisconnect: &'static ICDeviceCapability;
}

// NS_TYPED_ENUM
pub type ICSessionOptions = NSString;

extern "C" {
    pub static ICEnumerationChronologicalOrder: &'static ICSessionOptions;
}

// NS_TYPED_ENUM
pub type ICDeviceLocationOptions = NSString;

extern "C" {
    pub static ICDeviceLocationDescriptionUSB: &'static ICDeviceLocationOptions;
}

extern "C" {
    pub static ICDeviceLocationDescriptionFireWire: &'static ICDeviceLocationOptions;
}

extern "C" {
    pub static ICDeviceLocationDescriptionBluetooth: &'static ICDeviceLocationOptions;
}

extern "C" {
    pub static ICDeviceLocationDescriptionMassStorage: &'static ICDeviceLocationOptions;
}

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICDevice;

    unsafe impl ClassType for ICDevice {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICDevice {}

extern_methods!(
    unsafe impl ICDevice {
        #[method_id(@__retain_semantics Other delegate)]
        pub unsafe fn delegate(&self) -> Option<Retained<ProtocolObject<dyn ICDeviceDelegate>>>;

        #[method(setDelegate:)]
        pub unsafe fn setDelegate(&self, delegate: Option<&ProtocolObject<dyn ICDeviceDelegate>>);

        #[method(type)]
        pub unsafe fn r#type(&self) -> ICDeviceType;

        #[method_id(@__retain_semantics Other capabilities)]
        pub unsafe fn capabilities(&self) -> Retained<NSArray<NSString>>;

        #[method_id(@__retain_semantics Other name)]
        pub unsafe fn name(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other productKind)]
        pub unsafe fn productKind(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other systemSymbolName)]
        pub unsafe fn systemSymbolName(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other transportType)]
        pub unsafe fn transportType(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other UUIDString)]
        pub unsafe fn UUIDString(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other locationDescription)]
        pub unsafe fn locationDescription(&self) -> Option<Retained<NSString>>;

        #[method(hasOpenSession)]
        pub unsafe fn hasOpenSession(&self) -> bool;

        #[method_id(@__retain_semantics Other userData)]
        pub unsafe fn userData(&self) -> Option<Retained<NSMutableDictionary>>;

        #[method_id(@__retain_semantics Other modulePath)]
        pub unsafe fn modulePath(&self) -> Retained<NSString>;

        #[method_id(@__retain_semantics Other moduleVersion)]
        pub unsafe fn moduleVersion(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other serialNumberString)]
        pub unsafe fn serialNumberString(&self) -> Option<Retained<NSString>>;

        #[method(usbLocationID)]
        pub unsafe fn usbLocationID(&self) -> c_int;

        #[method(usbProductID)]
        pub unsafe fn usbProductID(&self) -> c_int;

        #[method(usbVendorID)]
        pub unsafe fn usbVendorID(&self) -> c_int;

        #[method(requestOpenSession)]
        pub unsafe fn requestOpenSession(&self);

        #[method(requestCloseSession)]
        pub unsafe fn requestCloseSession(&self);

        #[method(requestEject)]
        pub unsafe fn requestEject(&self);

        #[cfg(feature = "block2")]
        #[method(requestOpenSessionWithOptions:completion:)]
        pub unsafe fn requestOpenSessionWithOptions_completion(
            &self,
            options: Option<&NSDictionary<ICSessionOptions, AnyObject>>,
            completion: &block2::Block<dyn Fn(*mut NSError)>,
        );

        #[cfg(feature = "block2")]
        #[method(requestCloseSessionWithOptions:completion:)]
        pub unsafe fn requestCloseSessionWithOptions_completion(
            &self,
            options: Option<&NSDictionary<ICSessionOptions, AnyObject>>,
            completion: &block2::Block<dyn Fn(*mut NSError)>,
        );

        #[cfg(feature = "block2")]
        #[method(requestEjectWithCompletion:)]
        pub unsafe fn requestEjectWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(*mut NSError)>,
        );

        #[method_id(@__retain_semantics Other autolaunchApplicationPath)]
        pub unsafe fn autolaunchApplicationPath(&self) -> Option<Retained<NSString>>;

        #[method(setAutolaunchApplicationPath:)]
        pub unsafe fn setAutolaunchApplicationPath(
            &self,
            autolaunch_application_path: Option<&NSString>,
        );

        #[method(isRemote)]
        pub unsafe fn isRemote(&self) -> bool;

        #[method_id(@__retain_semantics Other persistentIDString)]
        pub unsafe fn persistentIDString(&self) -> Option<Retained<NSString>>;

        #[method(requestSendMessage:outData:maxReturnedDataSize:sendMessageDelegate:didSendMessageSelector:contextInfo:)]
        pub unsafe fn requestSendMessage_outData_maxReturnedDataSize_sendMessageDelegate_didSendMessageSelector_contextInfo(
            &self,
            message_code: c_uint,
            data: &NSData,
            max_returned_data_size: c_uint,
            send_message_delegate: &AnyObject,
            selector: Sel,
            context_info: *mut c_void,
        );

        #[deprecated]
        #[method(requestEjectOrDisconnect)]
        pub unsafe fn requestEjectOrDisconnect(&self);

        #[deprecated = "Requesting a device yield is no longer avaialble"]
        #[method(requestYield)]
        pub unsafe fn requestYield(&self);

        #[deprecated = "Module executable architecture is no longer available"]
        #[method(moduleExecutableArchitecture)]
        pub unsafe fn moduleExecutableArchitecture(&self) -> c_int;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICDevice {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_protocol!(
    pub unsafe trait ICDeviceDelegate: NSObjectProtocol {
        #[method(device:didCloseSessionWithError:)]
        unsafe fn device_didCloseSessionWithError(
            &self,
            device: &ICDevice,
            error: Option<&NSError>,
        );

        #[method(didRemoveDevice:)]
        unsafe fn didRemoveDevice(&self, device: &ICDevice);

        #[method(device:didOpenSessionWithError:)]
        unsafe fn device_didOpenSessionWithError(&self, device: &ICDevice, error: Option<&NSError>);

        #[optional]
        #[method(deviceDidBecomeReady:)]
        unsafe fn deviceDidBecomeReady(&self, device: &ICDevice);

        #[optional]
        #[method(deviceDidChangeName:)]
        unsafe fn deviceDidChangeName(&self, device: &ICDevice);

        #[optional]
        #[method(device:didReceiveStatusInformation:)]
        unsafe fn device_didReceiveStatusInformation(
            &self,
            device: &ICDevice,
            status: &NSDictionary<ICDeviceStatus, AnyObject>,
        );

        #[optional]
        #[method(device:didEncounterError:)]
        unsafe fn device_didEncounterError(&self, device: &ICDevice, error: Option<&NSError>);

        #[optional]
        #[method(device:didEjectWithError:)]
        unsafe fn device_didEjectWithError(&self, device: &ICDevice, error: Option<&NSError>);

        #[deprecated = "Device sharing is no longer available"]
        #[optional]
        #[method(deviceDidChangeSharingState:)]
        unsafe fn deviceDidChangeSharingState(&self, device: &ICDevice);
    }

    unsafe impl ProtocolType for dyn ICDeviceDelegate {}
);
