//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_TYPED_ENUM
pub type ICAuthorizationStatus = NSString;

extern "C" {
    pub static ICAuthorizationStatusNotDetermined: &'static ICAuthorizationStatus;
}

extern "C" {
    pub static ICAuthorizationStatusRestricted: &'static ICAuthorizationStatus;
}

extern "C" {
    pub static ICAuthorizationStatusDenied: &'static ICAuthorizationStatus;
}

extern "C" {
    pub static ICAuthorizationStatusAuthorized: &'static ICAuthorizationStatus;
}

extern_protocol!(
    pub unsafe trait ICDeviceBrowserDelegate: NSObjectProtocol {
        #[cfg(feature = "ICDevice")]
        #[method(deviceBrowser:didAddDevice:moreComing:)]
        unsafe fn deviceBrowser_didAddDevice_moreComing(
            &self,
            browser: &ICDeviceBrowser,
            device: &ICDevice,
            more_coming: bool,
        );

        #[cfg(feature = "ICDevice")]
        #[method(deviceBrowser:didRemoveDevice:moreGoing:)]
        unsafe fn deviceBrowser_didRemoveDevice_moreGoing(
            &self,
            browser: &ICDeviceBrowser,
            device: &ICDevice,
            more_going: bool,
        );

        #[cfg(feature = "ICDevice")]
        #[optional]
        #[method(deviceBrowser:deviceDidChangeName:)]
        unsafe fn deviceBrowser_deviceDidChangeName(
            &self,
            browser: &ICDeviceBrowser,
            device: &ICDevice,
        );

        #[cfg(feature = "ICDevice")]
        #[deprecated = "deviceDidChangeSharingState will no longer be called"]
        #[optional]
        #[method(deviceBrowser:deviceDidChangeSharingState:)]
        unsafe fn deviceBrowser_deviceDidChangeSharingState(
            &self,
            browser: &ICDeviceBrowser,
            device: &ICDevice,
        );

        #[cfg(feature = "ICDevice")]
        #[optional]
        #[method(deviceBrowser:requestsSelectDevice:)]
        unsafe fn deviceBrowser_requestsSelectDevice(
            &self,
            browser: &ICDeviceBrowser,
            device: &ICDevice,
        );

        #[optional]
        #[method(deviceBrowserDidEnumerateLocalDevices:)]
        unsafe fn deviceBrowserDidEnumerateLocalDevices(&self, browser: &ICDeviceBrowser);

        #[optional]
        #[method(deviceBrowserWillSuspendOperations:)]
        unsafe fn deviceBrowserWillSuspendOperations(&self, browser: &ICDeviceBrowser);

        #[optional]
        #[method(deviceBrowserDidSuspendOperations:)]
        unsafe fn deviceBrowserDidSuspendOperations(&self, browser: &ICDeviceBrowser);

        #[optional]
        #[method(deviceBrowserDidCancelSuspendOperations:)]
        unsafe fn deviceBrowserDidCancelSuspendOperations(&self, browser: &ICDeviceBrowser);

        #[optional]
        #[method(deviceBrowserDidResumeOperations:)]
        unsafe fn deviceBrowserDidResumeOperations(&self, browser: &ICDeviceBrowser);
    }

    unsafe impl ProtocolType for dyn ICDeviceBrowserDelegate {}
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICDeviceBrowser;

    unsafe impl ClassType for ICDeviceBrowser {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICDeviceBrowser {}

extern_methods!(
    unsafe impl ICDeviceBrowser {
        #[method_id(@__retain_semantics Other delegate)]
        pub unsafe fn delegate(
            &self,
        ) -> Option<Retained<ProtocolObject<dyn ICDeviceBrowserDelegate>>>;

        #[method(setDelegate:)]
        pub unsafe fn setDelegate(
            &self,
            delegate: Option<&ProtocolObject<dyn ICDeviceBrowserDelegate>>,
        );

        #[method(isBrowsing)]
        pub unsafe fn isBrowsing(&self) -> bool;

        #[method(isSuspended)]
        pub unsafe fn isSuspended(&self) -> bool;

        #[cfg(feature = "ICDevice")]
        #[method(browsedDeviceTypeMask)]
        pub unsafe fn browsedDeviceTypeMask(&self) -> ICDeviceTypeMask;

        #[cfg(feature = "ICDevice")]
        #[method(setBrowsedDeviceTypeMask:)]
        pub unsafe fn setBrowsedDeviceTypeMask(&self, browsed_device_type_mask: ICDeviceTypeMask);

        #[cfg(feature = "ICDevice")]
        #[method_id(@__retain_semantics Other devices)]
        pub unsafe fn devices(&self) -> Option<Retained<NSArray<ICDevice>>>;

        #[cfg(feature = "ICDevice")]
        #[method_id(@__retain_semantics Other preferredDevice)]
        pub unsafe fn preferredDevice(&self) -> Option<Retained<ICDevice>>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method(start)]
        pub unsafe fn start(&self);

        #[method(stop)]
        pub unsafe fn stop(&self);

        #[method_id(@__retain_semantics Other contentsAuthorizationStatus)]
        pub unsafe fn contentsAuthorizationStatus(&self) -> Retained<ICAuthorizationStatus>;

        #[cfg(feature = "block2")]
        #[method(requestContentsAuthorizationWithCompletion:)]
        pub unsafe fn requestContentsAuthorizationWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(NonNull<ICAuthorizationStatus>)>,
        );

        #[method_id(@__retain_semantics Other controlAuthorizationStatus)]
        pub unsafe fn controlAuthorizationStatus(&self) -> Retained<ICAuthorizationStatus>;

        #[cfg(feature = "block2")]
        #[method(requestControlAuthorizationWithCompletion:)]
        pub unsafe fn requestControlAuthorizationWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(NonNull<ICAuthorizationStatus>)>,
        );

        #[cfg(feature = "block2")]
        #[method(resetContentsAuthorizationWithCompletion:)]
        pub unsafe fn resetContentsAuthorizationWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(NonNull<ICAuthorizationStatus>)>,
        );

        #[cfg(feature = "block2")]
        #[method(resetControlAuthorizationWithCompletion:)]
        pub unsafe fn resetControlAuthorizationWithCompletion(
            &self,
            completion: &block2::Block<dyn Fn(NonNull<ICAuthorizationStatus>)>,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICDeviceBrowser {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
