//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern "C" {
    pub static ICButtonTypeScan: &'static NSString;
}

extern "C" {
    pub static ICButtonTypeMail: &'static NSString;
}

extern "C" {
    pub static ICButtonTypeCopy: &'static NSString;
}

extern "C" {
    pub static ICButtonTypeWeb: &'static NSString;
}

extern "C" {
    pub static ICButtonTypePrint: &'static NSString;
}

extern "C" {
    pub static ICButtonTypeTransfer: &'static NSString;
}

extern "C" {
    pub static ICScannerStatusWarmingUp: &'static NSString;
}

extern "C" {
    pub static ICScannerStatusWarmUpDone: &'static NSString;
}

extern "C" {
    pub static ICScannerStatusRequestsOverviewScan: &'static NSString;
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerTransferMode(pub NSUInteger);
impl ICScannerTransferMode {
    #[doc(alias = "ICScannerTransferModeFileBased")]
    pub const FileBased: Self = Self(0);
    #[doc(alias = "ICScannerTransferModeMemoryBased")]
    pub const MemoryBased: Self = Self(1);
}

unsafe impl Encode for ICScannerTransferMode {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerTransferMode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_protocol!(
    #[cfg(feature = "ICDevice")]
    pub unsafe trait ICScannerDeviceDelegate: ICDeviceDelegate {
        #[optional]
        #[method(scannerDeviceDidBecomeAvailable:)]
        unsafe fn scannerDeviceDidBecomeAvailable(&self, scanner: &ICScannerDevice);

        #[cfg(feature = "ICScannerFunctionalUnits")]
        #[optional]
        #[method(scannerDevice:didSelectFunctionalUnit:error:)]
        unsafe fn scannerDevice_didSelectFunctionalUnit_error(
            &self,
            scanner: &ICScannerDevice,
            functional_unit: &ICScannerFunctionalUnit,
            error: Option<&NSError>,
        );

        #[deprecated = "Use didScanToURL: for file URLs and didScanToBandData: for memory based transfers"]
        #[optional]
        #[method(scannerDevice:didScanToURL:data:)]
        unsafe fn scannerDevice_didScanToURL_data(
            &self,
            scanner: &ICScannerDevice,
            url: &NSURL,
            data: &NSData,
        );

        #[optional]
        #[method(scannerDevice:didScanToURL:)]
        unsafe fn scannerDevice_didScanToURL(&self, scanner: &ICScannerDevice, url: &NSURL);

        #[cfg(feature = "ICScannerBandData")]
        #[optional]
        #[method(scannerDevice:didScanToBandData:)]
        unsafe fn scannerDevice_didScanToBandData(
            &self,
            scanner: &ICScannerDevice,
            data: &ICScannerBandData,
        );

        #[optional]
        #[method(scannerDevice:didCompleteOverviewScanWithError:)]
        unsafe fn scannerDevice_didCompleteOverviewScanWithError(
            &self,
            scanner: &ICScannerDevice,
            error: Option<&NSError>,
        );

        #[optional]
        #[method(scannerDevice:didCompleteScanWithError:)]
        unsafe fn scannerDevice_didCompleteScanWithError(
            &self,
            scanner: &ICScannerDevice,
            error: Option<&NSError>,
        );
    }

    #[cfg(feature = "ICDevice")]
    unsafe impl ProtocolType for dyn ICScannerDeviceDelegate {}
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "ICDevice")]
    pub struct ICScannerDevice;

    #[cfg(feature = "ICDevice")]
    unsafe impl ClassType for ICScannerDevice {
        #[inherits(NSObject)]
        type Super = ICDevice;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "ICDevice")]
unsafe impl NSObjectProtocol for ICScannerDevice {}

extern_methods!(
    #[cfg(feature = "ICDevice")]
    unsafe impl ICScannerDevice {
        #[method_id(@__retain_semantics Other availableFunctionalUnitTypes)]
        pub unsafe fn availableFunctionalUnitTypes(&self) -> Retained<NSArray<NSNumber>>;

        #[cfg(feature = "ICScannerFunctionalUnits")]
        #[method_id(@__retain_semantics Other selectedFunctionalUnit)]
        pub unsafe fn selectedFunctionalUnit(&self) -> Retained<ICScannerFunctionalUnit>;

        #[method(transferMode)]
        pub unsafe fn transferMode(&self) -> ICScannerTransferMode;

        #[method(setTransferMode:)]
        pub unsafe fn setTransferMode(&self, transfer_mode: ICScannerTransferMode);

        #[method(maxMemoryBandSize)]
        pub unsafe fn maxMemoryBandSize(&self) -> u32;

        #[method(setMaxMemoryBandSize:)]
        pub unsafe fn setMaxMemoryBandSize(&self, max_memory_band_size: u32);

        #[method_id(@__retain_semantics Other downloadsDirectory)]
        pub unsafe fn downloadsDirectory(&self) -> Retained<NSURL>;

        #[method(setDownloadsDirectory:)]
        pub unsafe fn setDownloadsDirectory(&self, downloads_directory: &NSURL);

        #[method_id(@__retain_semantics Other documentName)]
        pub unsafe fn documentName(&self) -> Retained<NSString>;

        #[method(setDocumentName:)]
        pub unsafe fn setDocumentName(&self, document_name: &NSString);

        #[method_id(@__retain_semantics Other documentUTI)]
        pub unsafe fn documentUTI(&self) -> Retained<NSString>;

        #[method(setDocumentUTI:)]
        pub unsafe fn setDocumentUTI(&self, document_uti: &NSString);

        #[method_id(@__retain_semantics Other defaultUsername)]
        pub unsafe fn defaultUsername(&self) -> Retained<NSString>;

        #[method(setDefaultUsername:)]
        pub unsafe fn setDefaultUsername(&self, default_username: &NSString);

        #[method(requestOpenSessionWithCredentials:password:)]
        pub unsafe fn requestOpenSessionWithCredentials_password(
            &self,
            username: &NSString,
            password: &NSString,
        );

        #[cfg(feature = "ICScannerFunctionalUnits")]
        #[method(requestSelectFunctionalUnit:)]
        pub unsafe fn requestSelectFunctionalUnit(&self, r#type: ICScannerFunctionalUnitType);

        #[method(requestOverviewScan)]
        pub unsafe fn requestOverviewScan(&self);

        #[method(requestScan)]
        pub unsafe fn requestScan(&self);

        #[method(cancelScan)]
        pub unsafe fn cancelScan(&self);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "ICDevice")]
    unsafe impl ICScannerDevice {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
