//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFunctionalUnitType(pub NSUInteger);
impl ICScannerFunctionalUnitType {
    #[doc(alias = "ICScannerFunctionalUnitTypeFlatbed")]
    pub const Flatbed: Self = Self(0);
    #[doc(alias = "ICScannerFunctionalUnitTypePositiveTransparency")]
    pub const PositiveTransparency: Self = Self(1);
    #[doc(alias = "ICScannerFunctionalUnitTypeNegativeTransparency")]
    pub const NegativeTransparency: Self = Self(2);
    #[doc(alias = "ICScannerFunctionalUnitTypeDocumentFeeder")]
    pub const DocumentFeeder: Self = Self(3);
}

unsafe impl Encode for ICScannerFunctionalUnitType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerFunctionalUnitType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerMeasurementUnit(pub NSUInteger);
impl ICScannerMeasurementUnit {
    #[doc(alias = "ICScannerMeasurementUnitInches")]
    pub const Inches: Self = Self(0);
    #[doc(alias = "ICScannerMeasurementUnitCentimeters")]
    pub const Centimeters: Self = Self(1);
    #[doc(alias = "ICScannerMeasurementUnitPicas")]
    pub const Picas: Self = Self(2);
    #[doc(alias = "ICScannerMeasurementUnitPoints")]
    pub const Points: Self = Self(3);
    #[doc(alias = "ICScannerMeasurementUnitTwips")]
    pub const Twips: Self = Self(4);
    #[doc(alias = "ICScannerMeasurementUnitPixels")]
    pub const Pixels: Self = Self(5);
}

unsafe impl Encode for ICScannerMeasurementUnit {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerMeasurementUnit {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerBitDepth(pub NSUInteger);
impl ICScannerBitDepth {
    pub const ICScannerBitDepth1Bit: Self = Self(1);
    pub const ICScannerBitDepth8Bits: Self = Self(8);
    pub const ICScannerBitDepth16Bits: Self = Self(16);
}

unsafe impl Encode for ICScannerBitDepth {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerBitDepth {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerColorDataFormatType(pub NSUInteger);
impl ICScannerColorDataFormatType {
    #[doc(alias = "ICScannerColorDataFormatTypeChunky")]
    pub const Chunky: Self = Self(0);
    #[doc(alias = "ICScannerColorDataFormatTypePlanar")]
    pub const Planar: Self = Self(1);
}

unsafe impl Encode for ICScannerColorDataFormatType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerColorDataFormatType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerPixelDataType(pub NSUInteger);
impl ICScannerPixelDataType {
    #[doc(alias = "ICScannerPixelDataTypeBW")]
    pub const BW: Self = Self(0);
    #[doc(alias = "ICScannerPixelDataTypeGray")]
    pub const Gray: Self = Self(1);
    #[doc(alias = "ICScannerPixelDataTypeRGB")]
    pub const RGB: Self = Self(2);
    #[doc(alias = "ICScannerPixelDataTypePalette")]
    pub const Palette: Self = Self(3);
    #[doc(alias = "ICScannerPixelDataTypeCMY")]
    pub const CMY: Self = Self(4);
    #[doc(alias = "ICScannerPixelDataTypeCMYK")]
    pub const CMYK: Self = Self(5);
    #[doc(alias = "ICScannerPixelDataTypeYUV")]
    pub const YUV: Self = Self(6);
    #[doc(alias = "ICScannerPixelDataTypeYUVK")]
    pub const YUVK: Self = Self(7);
    #[doc(alias = "ICScannerPixelDataTypeCIEXYZ")]
    pub const CIEXYZ: Self = Self(8);
}

unsafe impl Encode for ICScannerPixelDataType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerPixelDataType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerDocumentType(pub NSUInteger);
impl ICScannerDocumentType {
    #[doc(alias = "ICScannerDocumentTypeDefault")]
    pub const Default: Self = Self(0);
    #[doc(alias = "ICScannerDocumentTypeA4")]
    pub const A4: Self = Self(1);
    #[doc(alias = "ICScannerDocumentTypeB5")]
    pub const B5: Self = Self(2);
    #[doc(alias = "ICScannerDocumentTypeUSLetter")]
    pub const USLetter: Self = Self(3);
    #[doc(alias = "ICScannerDocumentTypeUSLegal")]
    pub const USLegal: Self = Self(4);
    #[doc(alias = "ICScannerDocumentTypeA5")]
    pub const A5: Self = Self(5);
    #[doc(alias = "ICScannerDocumentTypeISOB4")]
    pub const ISOB4: Self = Self(6);
    #[doc(alias = "ICScannerDocumentTypeISOB6")]
    pub const ISOB6: Self = Self(7);
    #[doc(alias = "ICScannerDocumentTypeUSLedger")]
    pub const USLedger: Self = Self(9);
    #[doc(alias = "ICScannerDocumentTypeUSExecutive")]
    pub const USExecutive: Self = Self(10);
    #[doc(alias = "ICScannerDocumentTypeA3")]
    pub const A3: Self = Self(11);
    #[doc(alias = "ICScannerDocumentTypeISOB3")]
    pub const ISOB3: Self = Self(12);
    #[doc(alias = "ICScannerDocumentTypeA6")]
    pub const A6: Self = Self(13);
    #[doc(alias = "ICScannerDocumentTypeC4")]
    pub const C4: Self = Self(14);
    #[doc(alias = "ICScannerDocumentTypeC5")]
    pub const C5: Self = Self(15);
    #[doc(alias = "ICScannerDocumentTypeC6")]
    pub const C6: Self = Self(16);
    pub const ICScannerDocumentType4A0: Self = Self(17);
    pub const ICScannerDocumentType2A0: Self = Self(18);
    #[doc(alias = "ICScannerDocumentTypeA0")]
    pub const A0: Self = Self(19);
    #[doc(alias = "ICScannerDocumentTypeA1")]
    pub const A1: Self = Self(20);
    #[doc(alias = "ICScannerDocumentTypeA2")]
    pub const A2: Self = Self(21);
    #[doc(alias = "ICScannerDocumentTypeA7")]
    pub const A7: Self = Self(22);
    #[doc(alias = "ICScannerDocumentTypeA8")]
    pub const A8: Self = Self(23);
    #[doc(alias = "ICScannerDocumentTypeA9")]
    pub const A9: Self = Self(24);
    pub const ICScannerDocumentType10: Self = Self(25);
    #[doc(alias = "ICScannerDocumentTypeISOB0")]
    pub const ISOB0: Self = Self(26);
    #[doc(alias = "ICScannerDocumentTypeISOB1")]
    pub const ISOB1: Self = Self(27);
    #[doc(alias = "ICScannerDocumentTypeISOB2")]
    pub const ISOB2: Self = Self(28);
    #[doc(alias = "ICScannerDocumentTypeISOB5")]
    pub const ISOB5: Self = Self(29);
    #[doc(alias = "ICScannerDocumentTypeISOB7")]
    pub const ISOB7: Self = Self(30);
    #[doc(alias = "ICScannerDocumentTypeISOB8")]
    pub const ISOB8: Self = Self(31);
    #[doc(alias = "ICScannerDocumentTypeISOB9")]
    pub const ISOB9: Self = Self(32);
    #[doc(alias = "ICScannerDocumentTypeISOB10")]
    pub const ISOB10: Self = Self(33);
    #[doc(alias = "ICScannerDocumentTypeJISB0")]
    pub const JISB0: Self = Self(34);
    #[doc(alias = "ICScannerDocumentTypeJISB1")]
    pub const JISB1: Self = Self(35);
    #[doc(alias = "ICScannerDocumentTypeJISB2")]
    pub const JISB2: Self = Self(36);
    #[doc(alias = "ICScannerDocumentTypeJISB3")]
    pub const JISB3: Self = Self(37);
    #[doc(alias = "ICScannerDocumentTypeJISB4")]
    pub const JISB4: Self = Self(38);
    #[doc(alias = "ICScannerDocumentTypeJISB6")]
    pub const JISB6: Self = Self(39);
    #[doc(alias = "ICScannerDocumentTypeJISB7")]
    pub const JISB7: Self = Self(40);
    #[doc(alias = "ICScannerDocumentTypeJISB8")]
    pub const JISB8: Self = Self(41);
    #[doc(alias = "ICScannerDocumentTypeJISB9")]
    pub const JISB9: Self = Self(42);
    #[doc(alias = "ICScannerDocumentTypeJISB10")]
    pub const JISB10: Self = Self(43);
    #[doc(alias = "ICScannerDocumentTypeC0")]
    pub const C0: Self = Self(44);
    #[doc(alias = "ICScannerDocumentTypeC1")]
    pub const C1: Self = Self(45);
    #[doc(alias = "ICScannerDocumentTypeC2")]
    pub const C2: Self = Self(46);
    #[doc(alias = "ICScannerDocumentTypeC3")]
    pub const C3: Self = Self(47);
    #[doc(alias = "ICScannerDocumentTypeC7")]
    pub const C7: Self = Self(48);
    #[doc(alias = "ICScannerDocumentTypeC8")]
    pub const C8: Self = Self(49);
    #[doc(alias = "ICScannerDocumentTypeC9")]
    pub const C9: Self = Self(50);
    #[doc(alias = "ICScannerDocumentTypeC10")]
    pub const C10: Self = Self(51);
    #[doc(alias = "ICScannerDocumentTypeUSStatement")]
    pub const USStatement: Self = Self(52);
    #[doc(alias = "ICScannerDocumentTypeBusinessCard")]
    pub const BusinessCard: Self = Self(53);
    #[doc(alias = "ICScannerDocumentTypeE")]
    pub const E: Self = Self(60);
    pub const ICScannerDocumentType3R: Self = Self(61);
    pub const ICScannerDocumentType4R: Self = Self(62);
    pub const ICScannerDocumentType5R: Self = Self(63);
    pub const ICScannerDocumentType6R: Self = Self(64);
    pub const ICScannerDocumentType8R: Self = Self(65);
    #[doc(alias = "ICScannerDocumentTypeS8R")]
    pub const S8R: Self = Self(66);
    pub const ICScannerDocumentType10R: Self = Self(67);
    #[doc(alias = "ICScannerDocumentTypeS10R")]
    pub const S10R: Self = Self(68);
    pub const ICScannerDocumentType11R: Self = Self(69);
    pub const ICScannerDocumentType12R: Self = Self(70);
    #[doc(alias = "ICScannerDocumentTypeS12R")]
    pub const S12R: Self = Self(71);
    pub const ICScannerDocumentType110: Self = Self(72);
    #[doc(alias = "ICScannerDocumentTypeAPSH")]
    pub const APSH: Self = Self(73);
    #[doc(alias = "ICScannerDocumentTypeAPSC")]
    pub const APSC: Self = Self(74);
    #[doc(alias = "ICScannerDocumentTypeAPSP")]
    pub const APSP: Self = Self(75);
    pub const ICScannerDocumentType135: Self = Self(76);
    #[doc(alias = "ICScannerDocumentTypeMF")]
    pub const MF: Self = Self(77);
    #[doc(alias = "ICScannerDocumentTypeLF")]
    pub const LF: Self = Self(78);
}

unsafe impl Encode for ICScannerDocumentType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerDocumentType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFunctionalUnitState(pub NSUInteger);
impl ICScannerFunctionalUnitState {
    #[doc(alias = "ICScannerFunctionalUnitStateReady")]
    pub const Ready: Self = Self(1 << 0);
    #[doc(alias = "ICScannerFunctionalUnitStateScanInProgress")]
    pub const ScanInProgress: Self = Self(1 << 1);
    #[doc(alias = "ICScannerFunctionalUnitStateOverviewScanInProgress")]
    pub const OverviewScanInProgress: Self = Self(1 << 2);
}

unsafe impl Encode for ICScannerFunctionalUnitState {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerFunctionalUnitState {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFeatureType(pub NSUInteger);
impl ICScannerFeatureType {
    #[doc(alias = "ICScannerFeatureTypeEnumeration")]
    pub const Enumeration: Self = Self(0);
    #[doc(alias = "ICScannerFeatureTypeRange")]
    pub const Range: Self = Self(1);
    #[doc(alias = "ICScannerFeatureTypeBoolean")]
    pub const Boolean: Self = Self(2);
    #[doc(alias = "ICScannerFeatureTypeTemplate")]
    pub const Template: Self = Self(3);
}

unsafe impl Encode for ICScannerFeatureType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for ICScannerFeatureType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFeature;

    unsafe impl ClassType for ICScannerFeature {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFeature {}

extern_methods!(
    unsafe impl ICScannerFeature {
        #[method(type)]
        pub unsafe fn r#type(&self) -> ICScannerFeatureType;

        #[method_id(@__retain_semantics Other internalName)]
        pub unsafe fn internalName(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other humanReadableName)]
        pub unsafe fn humanReadableName(&self) -> Option<Retained<NSString>>;

        #[method_id(@__retain_semantics Other tooltip)]
        pub unsafe fn tooltip(&self) -> Option<Retained<NSString>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFeature {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFeatureEnumeration;

    unsafe impl ClassType for ICScannerFeatureEnumeration {
        #[inherits(NSObject)]
        type Super = ICScannerFeature;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFeatureEnumeration {}

extern_methods!(
    unsafe impl ICScannerFeatureEnumeration {
        #[method_id(@__retain_semantics Other currentValue)]
        pub unsafe fn currentValue(&self) -> Retained<AnyObject>;

        #[method(setCurrentValue:)]
        pub unsafe fn setCurrentValue(&self, current_value: &AnyObject);

        #[method_id(@__retain_semantics Other defaultValue)]
        pub unsafe fn defaultValue(&self) -> Retained<AnyObject>;

        #[method_id(@__retain_semantics Other values)]
        pub unsafe fn values(&self) -> Retained<NSArray<NSNumber>>;

        #[method_id(@__retain_semantics Other menuItemLabels)]
        pub unsafe fn menuItemLabels(&self) -> Retained<NSArray<NSString>>;

        #[method_id(@__retain_semantics Other menuItemLabelsTooltips)]
        pub unsafe fn menuItemLabelsTooltips(&self) -> Retained<NSArray<NSString>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFeatureEnumeration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFeatureRange;

    unsafe impl ClassType for ICScannerFeatureRange {
        #[inherits(NSObject)]
        type Super = ICScannerFeature;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFeatureRange {}

extern_methods!(
    unsafe impl ICScannerFeatureRange {
        #[method(currentValue)]
        pub unsafe fn currentValue(&self) -> CGFloat;

        #[method(setCurrentValue:)]
        pub unsafe fn setCurrentValue(&self, current_value: CGFloat);

        #[method(defaultValue)]
        pub unsafe fn defaultValue(&self) -> CGFloat;

        #[method(minValue)]
        pub unsafe fn minValue(&self) -> CGFloat;

        #[method(maxValue)]
        pub unsafe fn maxValue(&self) -> CGFloat;

        #[method(stepSize)]
        pub unsafe fn stepSize(&self) -> CGFloat;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFeatureRange {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFeatureBoolean;

    unsafe impl ClassType for ICScannerFeatureBoolean {
        #[inherits(NSObject)]
        type Super = ICScannerFeature;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFeatureBoolean {}

extern_methods!(
    unsafe impl ICScannerFeatureBoolean {
        #[method(value)]
        pub unsafe fn value(&self) -> bool;

        #[method(setValue:)]
        pub unsafe fn setValue(&self, value: bool);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFeatureBoolean {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFeatureTemplate;

    unsafe impl ClassType for ICScannerFeatureTemplate {
        #[inherits(NSObject)]
        type Super = ICScannerFeature;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFeatureTemplate {}

extern_methods!(
    unsafe impl ICScannerFeatureTemplate {
        #[method_id(@__retain_semantics Other targets)]
        pub unsafe fn targets(&self) -> Retained<NSArray<NSMutableArray>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFeatureTemplate {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFunctionalUnit;

    unsafe impl ClassType for ICScannerFunctionalUnit {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFunctionalUnit {}

extern_methods!(
    unsafe impl ICScannerFunctionalUnit {
        #[method(type)]
        pub unsafe fn r#type(&self) -> ICScannerFunctionalUnitType;

        #[method(pixelDataType)]
        pub unsafe fn pixelDataType(&self) -> ICScannerPixelDataType;

        #[method(setPixelDataType:)]
        pub unsafe fn setPixelDataType(&self, pixel_data_type: ICScannerPixelDataType);

        #[method_id(@__retain_semantics Other supportedBitDepths)]
        pub unsafe fn supportedBitDepths(&self) -> Retained<NSIndexSet>;

        #[method(bitDepth)]
        pub unsafe fn bitDepth(&self) -> ICScannerBitDepth;

        #[method(setBitDepth:)]
        pub unsafe fn setBitDepth(&self, bit_depth: ICScannerBitDepth);

        #[method_id(@__retain_semantics Other supportedMeasurementUnits)]
        pub unsafe fn supportedMeasurementUnits(&self) -> Retained<NSIndexSet>;

        #[method(measurementUnit)]
        pub unsafe fn measurementUnit(&self) -> ICScannerMeasurementUnit;

        #[method(setMeasurementUnit:)]
        pub unsafe fn setMeasurementUnit(&self, measurement_unit: ICScannerMeasurementUnit);

        #[method_id(@__retain_semantics Other supportedResolutions)]
        pub unsafe fn supportedResolutions(&self) -> Retained<NSIndexSet>;

        #[method_id(@__retain_semantics Other preferredResolutions)]
        pub unsafe fn preferredResolutions(&self) -> Retained<NSIndexSet>;

        #[method(resolution)]
        pub unsafe fn resolution(&self) -> NSUInteger;

        #[method(setResolution:)]
        pub unsafe fn setResolution(&self, resolution: NSUInteger);

        #[method(nativeXResolution)]
        pub unsafe fn nativeXResolution(&self) -> NSUInteger;

        #[method(nativeYResolution)]
        pub unsafe fn nativeYResolution(&self) -> NSUInteger;

        #[method_id(@__retain_semantics Other supportedScaleFactors)]
        pub unsafe fn supportedScaleFactors(&self) -> Retained<NSIndexSet>;

        #[method_id(@__retain_semantics Other preferredScaleFactors)]
        pub unsafe fn preferredScaleFactors(&self) -> Retained<NSIndexSet>;

        #[method(scaleFactor)]
        pub unsafe fn scaleFactor(&self) -> NSUInteger;

        #[method(setScaleFactor:)]
        pub unsafe fn setScaleFactor(&self, scale_factor: NSUInteger);

        #[method_id(@__retain_semantics Other templates)]
        pub unsafe fn templates(&self) -> Retained<NSArray<ICScannerFeatureTemplate>>;

        #[method_id(@__retain_semantics Other vendorFeatures)]
        pub unsafe fn vendorFeatures(&self) -> Option<Retained<NSArray<ICScannerFeature>>>;

        #[method(physicalSize)]
        pub unsafe fn physicalSize(&self) -> NSSize;

        #[method(scanArea)]
        pub unsafe fn scanArea(&self) -> NSRect;

        #[method(setScanArea:)]
        pub unsafe fn setScanArea(&self, scan_area: NSRect);

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(scanAreaOrientation)]
        pub unsafe fn scanAreaOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(setScanAreaOrientation:)]
        pub unsafe fn setScanAreaOrientation(&self, scan_area_orientation: ICEXIFOrientationType);

        #[method(acceptsThresholdForBlackAndWhiteScanning)]
        pub unsafe fn acceptsThresholdForBlackAndWhiteScanning(&self) -> bool;

        #[method(usesThresholdForBlackAndWhiteScanning)]
        pub unsafe fn usesThresholdForBlackAndWhiteScanning(&self) -> bool;

        #[method(setUsesThresholdForBlackAndWhiteScanning:)]
        pub unsafe fn setUsesThresholdForBlackAndWhiteScanning(
            &self,
            uses_threshold_for_black_and_white_scanning: bool,
        );

        #[method(defaultThresholdForBlackAndWhiteScanning)]
        pub unsafe fn defaultThresholdForBlackAndWhiteScanning(&self) -> c_uchar;

        #[method(thresholdForBlackAndWhiteScanning)]
        pub unsafe fn thresholdForBlackAndWhiteScanning(&self) -> c_uchar;

        #[method(setThresholdForBlackAndWhiteScanning:)]
        pub unsafe fn setThresholdForBlackAndWhiteScanning(
            &self,
            threshold_for_black_and_white_scanning: c_uchar,
        );

        #[method(state)]
        pub unsafe fn state(&self) -> ICScannerFunctionalUnitState;

        #[method(scanInProgress)]
        pub unsafe fn scanInProgress(&self) -> bool;

        #[method(scanProgressPercentDone)]
        pub unsafe fn scanProgressPercentDone(&self) -> CGFloat;

        #[method(canPerformOverviewScan)]
        pub unsafe fn canPerformOverviewScan(&self) -> bool;

        #[method(overviewScanInProgress)]
        pub unsafe fn overviewScanInProgress(&self) -> bool;

        #[method(overviewResolution)]
        pub unsafe fn overviewResolution(&self) -> NSUInteger;

        #[method(setOverviewResolution:)]
        pub unsafe fn setOverviewResolution(&self, overview_resolution: NSUInteger);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFunctionalUnit {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFunctionalUnitFlatbed;

    unsafe impl ClassType for ICScannerFunctionalUnitFlatbed {
        #[inherits(NSObject)]
        type Super = ICScannerFunctionalUnit;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFunctionalUnitFlatbed {}

extern_methods!(
    unsafe impl ICScannerFunctionalUnitFlatbed {
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFunctionalUnitFlatbed {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFunctionalUnitPositiveTransparency;

    unsafe impl ClassType for ICScannerFunctionalUnitPositiveTransparency {
        #[inherits(NSObject)]
        type Super = ICScannerFunctionalUnit;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFunctionalUnitPositiveTransparency {}

extern_methods!(
    unsafe impl ICScannerFunctionalUnitPositiveTransparency {
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFunctionalUnitPositiveTransparency {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFunctionalUnitNegativeTransparency;

    unsafe impl ClassType for ICScannerFunctionalUnitNegativeTransparency {
        #[inherits(NSObject)]
        type Super = ICScannerFunctionalUnit;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFunctionalUnitNegativeTransparency {}

extern_methods!(
    unsafe impl ICScannerFunctionalUnitNegativeTransparency {
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFunctionalUnitNegativeTransparency {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerFunctionalUnitDocumentFeeder;

    unsafe impl ClassType for ICScannerFunctionalUnitDocumentFeeder {
        #[inherits(NSObject)]
        type Super = ICScannerFunctionalUnit;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerFunctionalUnitDocumentFeeder {}

extern_methods!(
    unsafe impl ICScannerFunctionalUnitDocumentFeeder {
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;

        #[method(supportsDuplexScanning)]
        pub unsafe fn supportsDuplexScanning(&self) -> bool;

        #[method(duplexScanningEnabled)]
        pub unsafe fn duplexScanningEnabled(&self) -> bool;

        #[method(setDuplexScanningEnabled:)]
        pub unsafe fn setDuplexScanningEnabled(&self, duplex_scanning_enabled: bool);

        #[method(documentLoaded)]
        pub unsafe fn documentLoaded(&self) -> bool;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(oddPageOrientation)]
        pub unsafe fn oddPageOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(setOddPageOrientation:)]
        pub unsafe fn setOddPageOrientation(&self, odd_page_orientation: ICEXIFOrientationType);

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(evenPageOrientation)]
        pub unsafe fn evenPageOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        #[method(setEvenPageOrientation:)]
        pub unsafe fn setEvenPageOrientation(&self, even_page_orientation: ICEXIFOrientationType);

        #[method(reverseFeederPageOrder)]
        pub unsafe fn reverseFeederPageOrder(&self) -> bool;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerFunctionalUnitDocumentFeeder {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
