//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;
#[cfg(feature = "objc2-core-graphics")]
use objc2_core_graphics::*;
use objc2_foundation::*;

use crate::*;

/// Scanner Functional Unit Types
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunittype?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFunctionalUnitType(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerFunctionalUnitType {
    #[doc(alias = "ICScannerFunctionalUnitTypeFlatbed")]
    pub const Flatbed: Self = Self(0);
    #[doc(alias = "ICScannerFunctionalUnitTypePositiveTransparency")]
    pub const PositiveTransparency: Self = Self(1);
    #[doc(alias = "ICScannerFunctionalUnitTypeNegativeTransparency")]
    pub const NegativeTransparency: Self = Self(2);
    #[doc(alias = "ICScannerFunctionalUnitTypeDocumentFeeder")]
    pub const DocumentFeeder: Self = Self(3);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerFunctionalUnitType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerFunctionalUnitType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Unit of measurement used by the scanner. This corresponds to values used for ICAP_UNITS as defined in the TWAIN Specification.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannermeasurementunit?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerMeasurementUnit(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerMeasurementUnit {
    #[doc(alias = "ICScannerMeasurementUnitInches")]
    pub const Inches: Self = Self(0);
    #[doc(alias = "ICScannerMeasurementUnitCentimeters")]
    pub const Centimeters: Self = Self(1);
    #[doc(alias = "ICScannerMeasurementUnitPicas")]
    pub const Picas: Self = Self(2);
    #[doc(alias = "ICScannerMeasurementUnitPoints")]
    pub const Points: Self = Self(3);
    #[doc(alias = "ICScannerMeasurementUnitTwips")]
    pub const Twips: Self = Self(4);
    #[doc(alias = "ICScannerMeasurementUnitPixels")]
    pub const Pixels: Self = Self(5);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerMeasurementUnit {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerMeasurementUnit {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Bits per channel in the scanned image.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerbitdepth?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerBitDepth(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerBitDepth {
    pub const ICScannerBitDepth1Bit: Self = Self(1);
    pub const ICScannerBitDepth8Bits: Self = Self(8);
    pub const ICScannerBitDepth16Bits: Self = Self(16);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerBitDepth {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerBitDepth {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Identifies color data formats. Only relevant for multi-channel data. Corresponds to "ICAP_PLANARCHUNKY" of the TWAIN Specification.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannercolordataformattype?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerColorDataFormatType(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerColorDataFormatType {
    #[doc(alias = "ICScannerColorDataFormatTypeChunky")]
    pub const Chunky: Self = Self(0);
    #[doc(alias = "ICScannerColorDataFormatTypePlanar")]
    pub const Planar: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerColorDataFormatType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerColorDataFormatType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Pixel data types. Corresponds to "ICAP_PIXELTYPE" of the TWAIN Specification.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerpixeldatatype?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerPixelDataType(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerPixelDataType {
    #[doc(alias = "ICScannerPixelDataTypeBW")]
    pub const BW: Self = Self(0);
    #[doc(alias = "ICScannerPixelDataTypeGray")]
    pub const Gray: Self = Self(1);
    #[doc(alias = "ICScannerPixelDataTypeRGB")]
    pub const RGB: Self = Self(2);
    #[doc(alias = "ICScannerPixelDataTypePalette")]
    pub const Palette: Self = Self(3);
    #[doc(alias = "ICScannerPixelDataTypeCMY")]
    pub const CMY: Self = Self(4);
    #[doc(alias = "ICScannerPixelDataTypeCMYK")]
    pub const CMYK: Self = Self(5);
    #[doc(alias = "ICScannerPixelDataTypeYUV")]
    pub const YUV: Self = Self(6);
    #[doc(alias = "ICScannerPixelDataTypeYUVK")]
    pub const YUVK: Self = Self(7);
    #[doc(alias = "ICScannerPixelDataTypeCIEXYZ")]
    pub const CIEXYZ: Self = Self(8);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerPixelDataType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerPixelDataType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Document size types. Corresponds to "ICAP_SUPPORTEDSIZES" used by the Image Catpure scanner modules. Also refer to TWAIN 1.9 Specification, page 9-483.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerdocumenttype?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerDocumentType(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerDocumentType {
    #[doc(alias = "ICScannerDocumentTypeDefault")]
    pub const Default: Self = Self(0);
    #[doc(alias = "ICScannerDocumentTypeA4")]
    pub const A4: Self = Self(1);
    #[doc(alias = "ICScannerDocumentTypeB5")]
    pub const B5: Self = Self(2);
    #[doc(alias = "ICScannerDocumentTypeUSLetter")]
    pub const USLetter: Self = Self(3);
    #[doc(alias = "ICScannerDocumentTypeUSLegal")]
    pub const USLegal: Self = Self(4);
    #[doc(alias = "ICScannerDocumentTypeA5")]
    pub const A5: Self = Self(5);
    #[doc(alias = "ICScannerDocumentTypeISOB4")]
    pub const ISOB4: Self = Self(6);
    #[doc(alias = "ICScannerDocumentTypeISOB6")]
    pub const ISOB6: Self = Self(7);
    #[doc(alias = "ICScannerDocumentTypeUSLedger")]
    pub const USLedger: Self = Self(9);
    #[doc(alias = "ICScannerDocumentTypeUSExecutive")]
    pub const USExecutive: Self = Self(10);
    #[doc(alias = "ICScannerDocumentTypeA3")]
    pub const A3: Self = Self(11);
    #[doc(alias = "ICScannerDocumentTypeISOB3")]
    pub const ISOB3: Self = Self(12);
    #[doc(alias = "ICScannerDocumentTypeA6")]
    pub const A6: Self = Self(13);
    #[doc(alias = "ICScannerDocumentTypeC4")]
    pub const C4: Self = Self(14);
    #[doc(alias = "ICScannerDocumentTypeC5")]
    pub const C5: Self = Self(15);
    #[doc(alias = "ICScannerDocumentTypeC6")]
    pub const C6: Self = Self(16);
    pub const ICScannerDocumentType4A0: Self = Self(17);
    pub const ICScannerDocumentType2A0: Self = Self(18);
    #[doc(alias = "ICScannerDocumentTypeA0")]
    pub const A0: Self = Self(19);
    #[doc(alias = "ICScannerDocumentTypeA1")]
    pub const A1: Self = Self(20);
    #[doc(alias = "ICScannerDocumentTypeA2")]
    pub const A2: Self = Self(21);
    #[doc(alias = "ICScannerDocumentTypeA7")]
    pub const A7: Self = Self(22);
    #[doc(alias = "ICScannerDocumentTypeA8")]
    pub const A8: Self = Self(23);
    #[doc(alias = "ICScannerDocumentTypeA9")]
    pub const A9: Self = Self(24);
    pub const ICScannerDocumentType10: Self = Self(25);
    #[doc(alias = "ICScannerDocumentTypeISOB0")]
    pub const ISOB0: Self = Self(26);
    #[doc(alias = "ICScannerDocumentTypeISOB1")]
    pub const ISOB1: Self = Self(27);
    #[doc(alias = "ICScannerDocumentTypeISOB2")]
    pub const ISOB2: Self = Self(28);
    #[doc(alias = "ICScannerDocumentTypeISOB5")]
    pub const ISOB5: Self = Self(29);
    #[doc(alias = "ICScannerDocumentTypeISOB7")]
    pub const ISOB7: Self = Self(30);
    #[doc(alias = "ICScannerDocumentTypeISOB8")]
    pub const ISOB8: Self = Self(31);
    #[doc(alias = "ICScannerDocumentTypeISOB9")]
    pub const ISOB9: Self = Self(32);
    #[doc(alias = "ICScannerDocumentTypeISOB10")]
    pub const ISOB10: Self = Self(33);
    #[doc(alias = "ICScannerDocumentTypeJISB0")]
    pub const JISB0: Self = Self(34);
    #[doc(alias = "ICScannerDocumentTypeJISB1")]
    pub const JISB1: Self = Self(35);
    #[doc(alias = "ICScannerDocumentTypeJISB2")]
    pub const JISB2: Self = Self(36);
    #[doc(alias = "ICScannerDocumentTypeJISB3")]
    pub const JISB3: Self = Self(37);
    #[doc(alias = "ICScannerDocumentTypeJISB4")]
    pub const JISB4: Self = Self(38);
    #[doc(alias = "ICScannerDocumentTypeJISB6")]
    pub const JISB6: Self = Self(39);
    #[doc(alias = "ICScannerDocumentTypeJISB7")]
    pub const JISB7: Self = Self(40);
    #[doc(alias = "ICScannerDocumentTypeJISB8")]
    pub const JISB8: Self = Self(41);
    #[doc(alias = "ICScannerDocumentTypeJISB9")]
    pub const JISB9: Self = Self(42);
    #[doc(alias = "ICScannerDocumentTypeJISB10")]
    pub const JISB10: Self = Self(43);
    #[doc(alias = "ICScannerDocumentTypeC0")]
    pub const C0: Self = Self(44);
    #[doc(alias = "ICScannerDocumentTypeC1")]
    pub const C1: Self = Self(45);
    #[doc(alias = "ICScannerDocumentTypeC2")]
    pub const C2: Self = Self(46);
    #[doc(alias = "ICScannerDocumentTypeC3")]
    pub const C3: Self = Self(47);
    #[doc(alias = "ICScannerDocumentTypeC7")]
    pub const C7: Self = Self(48);
    #[doc(alias = "ICScannerDocumentTypeC8")]
    pub const C8: Self = Self(49);
    #[doc(alias = "ICScannerDocumentTypeC9")]
    pub const C9: Self = Self(50);
    #[doc(alias = "ICScannerDocumentTypeC10")]
    pub const C10: Self = Self(51);
    #[doc(alias = "ICScannerDocumentTypeUSStatement")]
    pub const USStatement: Self = Self(52);
    #[doc(alias = "ICScannerDocumentTypeBusinessCard")]
    pub const BusinessCard: Self = Self(53);
    #[doc(alias = "ICScannerDocumentTypeE")]
    pub const E: Self = Self(60);
    pub const ICScannerDocumentType3R: Self = Self(61);
    pub const ICScannerDocumentType4R: Self = Self(62);
    pub const ICScannerDocumentType5R: Self = Self(63);
    pub const ICScannerDocumentType6R: Self = Self(64);
    pub const ICScannerDocumentType8R: Self = Self(65);
    #[doc(alias = "ICScannerDocumentTypeS8R")]
    pub const S8R: Self = Self(66);
    pub const ICScannerDocumentType10R: Self = Self(67);
    #[doc(alias = "ICScannerDocumentTypeS10R")]
    pub const S10R: Self = Self(68);
    pub const ICScannerDocumentType11R: Self = Self(69);
    pub const ICScannerDocumentType12R: Self = Self(70);
    #[doc(alias = "ICScannerDocumentTypeS12R")]
    pub const S12R: Self = Self(71);
    pub const ICScannerDocumentType110: Self = Self(72);
    #[doc(alias = "ICScannerDocumentTypeAPSH")]
    pub const APSH: Self = Self(73);
    #[doc(alias = "ICScannerDocumentTypeAPSC")]
    pub const APSC: Self = Self(74);
    #[doc(alias = "ICScannerDocumentTypeAPSP")]
    pub const APSP: Self = Self(75);
    pub const ICScannerDocumentType135: Self = Self(76);
    #[doc(alias = "ICScannerDocumentTypeMF")]
    pub const MF: Self = Self(77);
    #[doc(alias = "ICScannerDocumentTypeLF")]
    pub const LF: Self = Self(78);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerDocumentType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerDocumentType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// A flag to indicate the scanner functional unit's state
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunitstate?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFunctionalUnitState(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerFunctionalUnitState {
    #[doc(alias = "ICScannerFunctionalUnitStateReady")]
    pub const Ready: Self = Self(1 << 0);
    #[doc(alias = "ICScannerFunctionalUnitStateScanInProgress")]
    pub const ScanInProgress: Self = Self(1 << 1);
    #[doc(alias = "ICScannerFunctionalUnitStateOverviewScanInProgress")]
    pub const OverviewScanInProgress: Self = Self(1 << 2);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerFunctionalUnitState {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerFunctionalUnitState {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Scanner Feature Types
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeaturetype?language=objc)
// NS_ENUM
#[cfg(feature = "objc2")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ICScannerFeatureType(pub NSUInteger);
#[cfg(feature = "objc2")]
impl ICScannerFeatureType {
    #[doc(alias = "ICScannerFeatureTypeEnumeration")]
    pub const Enumeration: Self = Self(0);
    #[doc(alias = "ICScannerFeatureTypeRange")]
    pub const Range: Self = Self(1);
    #[doc(alias = "ICScannerFeatureTypeBoolean")]
    pub const Boolean: Self = Self(2);
    #[doc(alias = "ICScannerFeatureTypeTemplate")]
    pub const Template: Self = Self(3);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ICScannerFeatureType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ICScannerFeatureType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFeature class is an abstract base class used to describe a scanner feature. ImageCaptureCore defines three concrete subclasses of ICScannerFeature: ICScannerFeatureEnumeration, ICScannerFeatureRange and ICScannerFeatureBoolean.
    ///
    /// The scanner functional units may have one or more instances of these classes to allow users to choose scanner-specific settings or operations before performing a scan.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeature?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFeature;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFeature {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeature {
        /// ￼Scanner feature type.
        #[method(type)]
        pub unsafe fn r#type(&self) -> ICScannerFeatureType;

        /// ￼The internal name of this feature.
        #[method_id(@__retain_semantics Other internalName)]
        pub unsafe fn internalName(&self) -> Option<Retained<NSString>>;

        /// The human readable name of this feature.
        #[method_id(@__retain_semantics Other humanReadableName)]
        pub unsafe fn humanReadableName(&self) -> Option<Retained<NSString>>;

        /// ￼Tooltip text describing the feature.
        #[method_id(@__retain_semantics Other tooltip)]
        pub unsafe fn tooltip(&self) -> Option<Retained<NSString>>;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeature {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFeatureEnumeration object is used to represent a feature of a scanner functional unit that can have one of several discrete values.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeatureenumeration?language=objc)
    #[unsafe(super(ICScannerFeature, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFeatureEnumeration;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFeatureEnumeration {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureEnumeration {
        /// The current value. The current value can be set to one of the possible values in the "values" property below￼.
        #[method_id(@__retain_semantics Other currentValue)]
        pub unsafe fn currentValue(&self) -> Retained<AnyObject>;

        /// Setter for [`currentValue`][Self::currentValue].
        #[method(setCurrentValue:)]
        pub unsafe fn setCurrentValue(&self, current_value: &AnyObject);

        /// ￼The default value. The default value can be set to one of the possible values in the "values" property below.
        #[method_id(@__retain_semantics Other defaultValue)]
        pub unsafe fn defaultValue(&self) -> Retained<AnyObject>;

        /// An array of possible values. All items in this array must be of same type￼.
        #[method_id(@__retain_semantics Other values)]
        pub unsafe fn values(&self) -> Retained<NSArray<NSNumber>>;

        /// ￼The human readable menu item labels to be used in a menu to allow the user to select the current value from an array of possible values.
        #[method_id(@__retain_semantics Other menuItemLabels)]
        pub unsafe fn menuItemLabels(&self) -> Retained<NSArray<NSString>>;

        /// ￼Tooltip text associated with the menu items.
        #[method_id(@__retain_semantics Other menuItemLabelsTooltips)]
        pub unsafe fn menuItemLabelsTooltips(&self) -> Retained<NSArray<NSString>>;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureEnumeration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFeatureRange object is used to represent a property of a scanner functional unit whose value lies within a range.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeaturerange?language=objc)
    #[unsafe(super(ICScannerFeature, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFeatureRange;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFeatureRange {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureRange {
        #[cfg(feature = "objc2-core-foundation")]
        /// ￼The current value. Attempting to set the current value to a value that is not coincident with a step will result in a value corresponding to the nearest step being assigned to the current value.
        #[method(currentValue)]
        pub unsafe fn currentValue(&self) -> CGFloat;

        #[cfg(feature = "objc2-core-foundation")]
        /// Setter for [`currentValue`][Self::currentValue].
        #[method(setCurrentValue:)]
        pub unsafe fn setCurrentValue(&self, current_value: CGFloat);

        #[cfg(feature = "objc2-core-foundation")]
        /// The default value￼. Attempting to set the default value to a value that is not coincident with a step will result in a value corresponding to the nearest step being assigned to the default value.
        #[method(defaultValue)]
        pub unsafe fn defaultValue(&self) -> CGFloat;

        #[cfg(feature = "objc2-core-foundation")]
        /// The minimum value.
        #[method(minValue)]
        pub unsafe fn minValue(&self) -> CGFloat;

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼The maximum value.
        #[method(maxValue)]
        pub unsafe fn maxValue(&self) -> CGFloat;

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼The step size.
        #[method(stepSize)]
        pub unsafe fn stepSize(&self) -> CGFloat;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureRange {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFeatureBoolean object is used to represent a property of a scanner functional unit whose value can be YES or NO.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeatureboolean?language=objc)
    #[unsafe(super(ICScannerFeature, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFeatureBoolean;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFeatureBoolean {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureBoolean {
        /// ￼The value of this feature.
        #[method(value)]
        pub unsafe fn value(&self) -> bool;

        /// Setter for [`value`][Self::value].
        #[method(setValue:)]
        pub unsafe fn setValue(&self, value: bool);
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureBoolean {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFeatureTemplate object is used to define a group of one or more rectangular scan areas that can be used with a scanner functional unit.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfeaturetemplate?language=objc)
    #[unsafe(super(ICScannerFeature, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFeatureTemplate;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFeatureTemplate {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureTemplate {
        #[method_id(@__retain_semantics Other targets)]
        pub unsafe fn targets(&self) -> Retained<NSArray<NSMutableArray>>;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFeatureTemplate {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFunctionalUnit is an abstract class that represents a scanner functiona unit. ImageCaptureCore defines three concrete subclasses of ICScannerFunctionalUnit: ICScannerFunctionalUnitFlatbed, ICScannerFunctionalUnitPositiveTransparency, ICScannerFunctionalUnitNegativeTransparency and ICScannerFunctionalUnitDocumentFeeder. ICScannerDevice creates instances of these concrete subclasses.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunit?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFunctionalUnit;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFunctionalUnit {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnit {
        /// ￼Functional unit type.
        #[method(type)]
        pub unsafe fn r#type(&self) -> ICScannerFunctionalUnitType;

        /// ￼The pixel data type.
        #[method(pixelDataType)]
        pub unsafe fn pixelDataType(&self) -> ICScannerPixelDataType;

        /// Setter for [`pixelDataType`][Self::pixelDataType].
        #[method(setPixelDataType:)]
        pub unsafe fn setPixelDataType(&self, pixel_data_type: ICScannerPixelDataType);

        /// ￼Supported bit depths. The values in this set are valid values defined by ICScannerBitDepth.
        #[method_id(@__retain_semantics Other supportedBitDepths)]
        pub unsafe fn supportedBitDepths(&self) -> Retained<NSIndexSet>;

        /// ￼The bit depth to use when performing the final scan. This will always be one of the supported bit depths.
        #[method(bitDepth)]
        pub unsafe fn bitDepth(&self) -> ICScannerBitDepth;

        /// Setter for [`bitDepth`][Self::bitDepth].
        #[method(setBitDepth:)]
        pub unsafe fn setBitDepth(&self, bit_depth: ICScannerBitDepth);

        /// ￼Supported measurement units. The values in this set are valid values defined by ICScannerMeasurementUnit.
        #[method_id(@__retain_semantics Other supportedMeasurementUnits)]
        pub unsafe fn supportedMeasurementUnits(&self) -> Retained<NSIndexSet>;

        /// ￼Current measurement unit. This will always be one of the supported measurement units.
        #[method(measurementUnit)]
        pub unsafe fn measurementUnit(&self) -> ICScannerMeasurementUnit;

        /// Setter for [`measurementUnit`][Self::measurementUnit].
        #[method(setMeasurementUnit:)]
        pub unsafe fn setMeasurementUnit(&self, measurement_unit: ICScannerMeasurementUnit);

        /// ￼Supported scan resolutions in DPI.
        #[method_id(@__retain_semantics Other supportedResolutions)]
        pub unsafe fn supportedResolutions(&self) -> Retained<NSIndexSet>;

        /// ￼Preferred scan resolutions in DPI.
        #[method_id(@__retain_semantics Other preferredResolutions)]
        pub unsafe fn preferredResolutions(&self) -> Retained<NSIndexSet>;

        /// ￼Current scan resolution. This will always be one of the supported resolution values.
        #[method(resolution)]
        pub unsafe fn resolution(&self) -> NSUInteger;

        /// Setter for [`resolution`][Self::resolution].
        #[method(setResolution:)]
        pub unsafe fn setResolution(&self, resolution: NSUInteger);

        /// ￼Optical resolution along the X axis.
        #[method(nativeXResolution)]
        pub unsafe fn nativeXResolution(&self) -> NSUInteger;

        /// ￼Optical resolution along the Y axis.
        #[method(nativeYResolution)]
        pub unsafe fn nativeYResolution(&self) -> NSUInteger;

        /// ￼Supported scale factors in percentage.
        #[method_id(@__retain_semantics Other supportedScaleFactors)]
        pub unsafe fn supportedScaleFactors(&self) -> Retained<NSIndexSet>;

        /// ￼Preferred scale factors in percentage.
        #[method_id(@__retain_semantics Other preferredScaleFactors)]
        pub unsafe fn preferredScaleFactors(&self) -> Retained<NSIndexSet>;

        /// ￼Current scale factor. This will always be one of the supported scale factor values.
        #[method(scaleFactor)]
        pub unsafe fn scaleFactor(&self) -> NSUInteger;

        /// Setter for [`scaleFactor`][Self::scaleFactor].
        #[method(setScaleFactor:)]
        pub unsafe fn setScaleFactor(&self, scale_factor: NSUInteger);

        /// An array of objects of type ICScannerFeatureTemplate.
        #[method_id(@__retain_semantics Other templates)]
        pub unsafe fn templates(&self) -> Retained<NSArray<ICScannerFeatureTemplate>>;

        /// An array of objects of type ICScannerFeature.
        #[method_id(@__retain_semantics Other vendorFeatures)]
        pub unsafe fn vendorFeatures(&self) -> Option<Retained<NSArray<ICScannerFeature>>>;

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Physical size of the scan area in current measurement unit.
        #[method(physicalSize)]
        pub unsafe fn physicalSize(&self) -> NSSize;

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼This property along with scanAreaOrientation describes the area to be scanned.
        #[method(scanArea)]
        pub unsafe fn scanArea(&self) -> NSRect;

        #[cfg(feature = "objc2-core-foundation")]
        /// Setter for [`scanArea`][Self::scanArea].
        #[method(setScanArea:)]
        pub unsafe fn setScanArea(&self, scan_area: NSRect);

        #[cfg(feature = "ImageCaptureConstants")]
        /// ￼Desired orientation of the scan area. This property along with scanArea describes the area to be scanned.
        ///
        /// This property is set to ICEXIFOrientation1 initially. This property is not used by the ICScannerFunctionalUnitDocumentFeeder subclass.
        #[method(scanAreaOrientation)]
        pub unsafe fn scanAreaOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        /// Setter for [`scanAreaOrientation`][Self::scanAreaOrientation].
        #[method(setScanAreaOrientation:)]
        pub unsafe fn setScanAreaOrientation(&self, scan_area_orientation: ICEXIFOrientationType);

        /// ￼Indicates if this functional unit accepts threshold value to be used when performing a scan in black
        /// &
        /// white.
        #[method(acceptsThresholdForBlackAndWhiteScanning)]
        pub unsafe fn acceptsThresholdForBlackAndWhiteScanning(&self) -> bool;

        /// ￼Indicates if this functional unit uses threshold value to be used when performing a scan in black
        /// &
        /// white.
        #[method(usesThresholdForBlackAndWhiteScanning)]
        pub unsafe fn usesThresholdForBlackAndWhiteScanning(&self) -> bool;

        /// Setter for [`usesThresholdForBlackAndWhiteScanning`][Self::usesThresholdForBlackAndWhiteScanning].
        #[method(setUsesThresholdForBlackAndWhiteScanning:)]
        pub unsafe fn setUsesThresholdForBlackAndWhiteScanning(
            &self,
            uses_threshold_for_black_and_white_scanning: bool,
        );

        /// ￼Default threshold value used when performing a scan in black
        /// &
        /// white. This value is from 0 to 255.
        #[method(defaultThresholdForBlackAndWhiteScanning)]
        pub unsafe fn defaultThresholdForBlackAndWhiteScanning(&self) -> c_uchar;

        /// ￼Threshold value to be used when performing a scan in black
        /// &
        /// white. This value should be from 0 to 255.
        #[method(thresholdForBlackAndWhiteScanning)]
        pub unsafe fn thresholdForBlackAndWhiteScanning(&self) -> c_uchar;

        /// Setter for [`thresholdForBlackAndWhiteScanning`][Self::thresholdForBlackAndWhiteScanning].
        #[method(setThresholdForBlackAndWhiteScanning:)]
        pub unsafe fn setThresholdForBlackAndWhiteScanning(
            &self,
            threshold_for_black_and_white_scanning: c_uchar,
        );

        /// ￼Indicates the current state of the functional unit.
        #[method(state)]
        pub unsafe fn state(&self) -> ICScannerFunctionalUnitState;

        /// ￼Indicates if a scan is in progress.
        #[method(scanInProgress)]
        pub unsafe fn scanInProgress(&self) -> bool;

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Indicates percentage of scan completed.
        #[method(scanProgressPercentDone)]
        pub unsafe fn scanProgressPercentDone(&self) -> CGFloat;

        /// ￼Indicates if this functional unit can perfrom an overview scan. Not all functional units can perform an overview scan. For example, a document feeder or a sheet feeder unit cannot perform an overview scan.
        #[method(canPerformOverviewScan)]
        pub unsafe fn canPerformOverviewScan(&self) -> bool;

        /// ￼Indicates if an overview scan is in progress.
        #[method(overviewScanInProgress)]
        pub unsafe fn overviewScanInProgress(&self) -> bool;

        #[cfg(feature = "objc2-core-graphics")]
        /// ￼Overview scan image. This property will be NULL for functional units that do not support overview scans.
        #[method(overviewImage)]
        pub unsafe fn overviewImage(&self) -> CGImageRef;

        /// ￼Overview image resolution. Value assigned to this will be contrained by resolutions allowed by the device.
        #[method(overviewResolution)]
        pub unsafe fn overviewResolution(&self) -> NSUInteger;

        /// Setter for [`overviewResolution`][Self::overviewResolution].
        #[method(setOverviewResolution:)]
        pub unsafe fn setOverviewResolution(&self, overview_resolution: NSUInteger);
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnit {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFunctionalUnitFlatbed is a concrete subclass of ICScannerFunctionalUnit class. ICScannerDevice creates instances of this class.
    ///
    /// This represents the flatbed  unit on the scanner.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunitflatbed?language=objc)
    #[unsafe(super(ICScannerFunctionalUnit, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFunctionalUnitFlatbed;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFunctionalUnitFlatbed {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitFlatbed {
        /// ￼Supported document types. The values in this set are valid values defined by ICScannerDocumentType.
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        /// ￼Current document type. This will always be one of the supported document types.
        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        /// Setter for [`documentType`][Self::documentType].
        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Document size of the current document type expressed in current measurement unit.
        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitFlatbed {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFunctionalUnitPositiveTransparency is a concrete subclass of ICScannerFunctionalUnit class. ICScannerDevice creates instances of this class.
    ///
    /// This represents the transparency unit on the scanner for scanning postives
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunitpositivetransparency?language=objc)
    #[unsafe(super(ICScannerFunctionalUnit, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFunctionalUnitPositiveTransparency;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFunctionalUnitPositiveTransparency {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitPositiveTransparency {
        /// ￼Supported document types. The values in this set are valid values defined by ICScannerDocumentType.
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        /// ￼Current document type. This will always be one of the supported document types.
        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        /// Setter for [`documentType`][Self::documentType].
        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Document size of the current document type expressed in current measurement unit.
        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitPositiveTransparency {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFunctionalUnitNegativeTransparency is a concrete subclass of ICScannerFunctionalUnit class. ICScannerDevice creates instances of this class.
    ///
    /// This represents the transparency unit on the scanner for scanning negatives.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunitnegativetransparency?language=objc)
    #[unsafe(super(ICScannerFunctionalUnit, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFunctionalUnitNegativeTransparency;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFunctionalUnitNegativeTransparency {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitNegativeTransparency {
        /// ￼Supported document types. The values in this set are valid values defined by ICScannerDocumentType.
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        /// ￼Current document type. This will always be one of the supported document types.
        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        /// Setter for [`documentType`][Self::documentType].
        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Document size of the current document type expressed in current measurement unit.
        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitNegativeTransparency {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

#[cfg(feature = "objc2")]
extern_class!(
    /// ICScannerFunctionalUnitDocumentFeeder is a concrete subclass of ICScannerFunctionalUnit class. ICScannerDevice creates instances of this class.
    ///
    /// This represents the document feeder unit on the scanner.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder?language=objc)
    #[unsafe(super(ICScannerFunctionalUnit, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "objc2")]
    pub struct ICScannerFunctionalUnitDocumentFeeder;
);

#[cfg(feature = "objc2")]
unsafe impl NSObjectProtocol for ICScannerFunctionalUnitDocumentFeeder {}

#[cfg(feature = "objc2")]
extern_methods!(
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitDocumentFeeder {
        /// ￼Supported document types. The values in this set are valid values defined by ICScannerDocumentType.
        #[method_id(@__retain_semantics Other supportedDocumentTypes)]
        pub unsafe fn supportedDocumentTypes(&self) -> Retained<NSIndexSet>;

        /// ￼Current document type. This will always be one of the supported document types.
        #[method(documentType)]
        pub unsafe fn documentType(&self) -> ICScannerDocumentType;

        /// Setter for [`documentType`][Self::documentType].
        #[method(setDocumentType:)]
        pub unsafe fn setDocumentType(&self, document_type: ICScannerDocumentType);

        #[cfg(feature = "objc2-core-foundation")]
        /// ￼Document size of the current document type expressed in current measurement unit.
        #[method(documentSize)]
        pub unsafe fn documentSize(&self) -> NSSize;

        /// ￼Indicates whether duplex scanning is supported.
        #[method(supportsDuplexScanning)]
        pub unsafe fn supportsDuplexScanning(&self) -> bool;

        /// ￼Indicates whether duplex scanning is enabled.
        #[method(duplexScanningEnabled)]
        pub unsafe fn duplexScanningEnabled(&self) -> bool;

        /// Setter for [`duplexScanningEnabled`][Self::duplexScanningEnabled].
        #[method(setDuplexScanningEnabled:)]
        pub unsafe fn setDuplexScanningEnabled(&self, duplex_scanning_enabled: bool);

        /// ￼Indicates whether the feeder has documents to scan.
        ///
        /// This value will change when the document is loaded or removed from the feeder, if the scanner module has the capability to detect this state.
        #[method(documentLoaded)]
        pub unsafe fn documentLoaded(&self) -> bool;

        #[cfg(feature = "ImageCaptureConstants")]
        /// ￼Desired orientation of the odd pages of the scanned document.
        ///
        /// This property is set to ICEXIFOrientation1 initially.
        #[method(oddPageOrientation)]
        pub unsafe fn oddPageOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        /// Setter for [`oddPageOrientation`][Self::oddPageOrientation].
        #[method(setOddPageOrientation:)]
        pub unsafe fn setOddPageOrientation(&self, odd_page_orientation: ICEXIFOrientationType);

        #[cfg(feature = "ImageCaptureConstants")]
        /// ￼Desired orientation of the even pages of the scanned document.
        ///
        /// This property is set to ICEXIFOrientation1 initially.
        #[method(evenPageOrientation)]
        pub unsafe fn evenPageOrientation(&self) -> ICEXIFOrientationType;

        #[cfg(feature = "ImageCaptureConstants")]
        /// Setter for [`evenPageOrientation`][Self::evenPageOrientation].
        #[method(setEvenPageOrientation:)]
        pub unsafe fn setEvenPageOrientation(&self, even_page_orientation: ICEXIFOrientationType);

        /// ￼Indicates whether the document feeder reads pages from back to front.
        #[method(reverseFeederPageOrder)]
        pub unsafe fn reverseFeederPageOrder(&self) -> bool;
    }
);

#[cfg(feature = "objc2")]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "objc2")]
    unsafe impl ICScannerFunctionalUnitDocumentFeeder {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
