//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct ICScannerBandData;

    unsafe impl ClassType for ICScannerBandData {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for ICScannerBandData {}

extern_methods!(
    unsafe impl ICScannerBandData {
        #[method(fullImageWidth)]
        pub unsafe fn fullImageWidth(&self) -> NSUInteger;

        #[method(fullImageHeight)]
        pub unsafe fn fullImageHeight(&self) -> NSUInteger;

        #[method(bitsPerPixel)]
        pub unsafe fn bitsPerPixel(&self) -> NSUInteger;

        #[method(bitsPerComponent)]
        pub unsafe fn bitsPerComponent(&self) -> NSUInteger;

        #[method(numComponents)]
        pub unsafe fn numComponents(&self) -> NSUInteger;

        #[method(isBigEndian)]
        pub unsafe fn isBigEndian(&self) -> bool;

        #[cfg(feature = "ICScannerFunctionalUnits")]
        #[method(pixelDataType)]
        pub unsafe fn pixelDataType(&self) -> ICScannerPixelDataType;

        #[method_id(@__retain_semantics Other colorSyncProfilePath)]
        pub unsafe fn colorSyncProfilePath(&self) -> Option<Retained<NSString>>;

        #[method(bytesPerRow)]
        pub unsafe fn bytesPerRow(&self) -> NSUInteger;

        #[method(dataStartRow)]
        pub unsafe fn dataStartRow(&self) -> NSUInteger;

        #[method(dataNumRows)]
        pub unsafe fn dataNumRows(&self) -> NSUInteger;

        #[method(dataSize)]
        pub unsafe fn dataSize(&self) -> NSUInteger;

        #[method_id(@__retain_semantics Other dataBuffer)]
        pub unsafe fn dataBuffer(&self) -> Option<Retained<NSData>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl ICScannerBandData {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
