// This file has been automatically generated by `objc2`'s `header-translator`.
// DO NOT EDIT

#![allow(unused_imports)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::identity_op)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::unportable_markdown)]
#![allow(rustdoc::invalid_html_tags)]

#[link(name = "ImageCaptureCore", kind = "framework")]
extern "C" {}

#[cfg(feature = "ICCameraDevice")]
#[path = "ICCameraDevice.rs"]
mod __ICCameraDevice;
#[cfg(feature = "ICCameraFile")]
#[path = "ICCameraFile.rs"]
mod __ICCameraFile;
#[cfg(feature = "ICCameraFolder")]
#[path = "ICCameraFolder.rs"]
mod __ICCameraFolder;
#[cfg(feature = "ICCameraItem")]
#[path = "ICCameraItem.rs"]
mod __ICCameraItem;
#[cfg(feature = "ICDevice")]
#[path = "ICDevice.rs"]
mod __ICDevice;
#[cfg(feature = "ICDeviceBrowser")]
#[path = "ICDeviceBrowser.rs"]
mod __ICDeviceBrowser;
#[cfg(feature = "ICScannerBandData")]
#[path = "ICScannerBandData.rs"]
mod __ICScannerBandData;
#[cfg(feature = "ICScannerDevice")]
#[path = "ICScannerDevice.rs"]
mod __ICScannerDevice;
#[cfg(feature = "ICScannerFunctionalUnits")]
#[path = "ICScannerFunctionalUnits.rs"]
mod __ICScannerFunctionalUnits;
#[cfg(feature = "ImageCaptureConstants")]
#[path = "ImageCaptureConstants.rs"]
mod __ImageCaptureConstants;
#[cfg(feature = "ImageCapturePlatform")]
#[path = "ImageCapturePlatform.rs"]
mod __ImageCapturePlatform;

#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDevice;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanAcceptPTPCommands;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanDeleteAllFiles;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanDeleteOneFile;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanReceiveFile;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanSyncClock;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanTakePicture;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceCanTakePictureUsingShutterReleaseOnCamera;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceDelegate;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceDownloadDelegate;
#[cfg(all(feature = "ICCameraDevice", feature = "ICDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICCameraDeviceSupportsHEIF;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteCanceled;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteError;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteErrorCanceled;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteErrorDeviceMissing;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteErrorFileMissing;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteErrorReadOnly;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteFailed;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteResult;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICDeleteSuccessful;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICMediaPresentation;
#[cfg(all(feature = "ICCameraDevice", feature = "objc2"))]
pub use self::__ICCameraDevice::ICUploadOption;
#[cfg(all(feature = "ICCameraFile", feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraFile::ICCameraFile;
#[cfg(all(
    feature = "ICCameraFolder",
    feature = "ICCameraItem",
    feature = "objc2"
))]
pub use self::__ICCameraFolder::ICCameraFolder;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICCameraItem;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICCameraItemMetadataOption;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICCameraItemThumbnailOption;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICDeleteAfterSuccessfulDownload;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICDownloadOption;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICDownloadSidecarFiles;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICDownloadsDirectoryURL;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICImageSourceShouldCache;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICImageSourceThumbnailMaxPixelSize;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICOverwrite;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICSaveAsFilename;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICSavedAncillaryFiles;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICSavedFilename;
#[cfg(all(feature = "ICCameraItem", feature = "objc2"))]
pub use self::__ICCameraItem::ICTruncateAfterSuccessfulDownload;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDevice;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceCanEjectOrDisconnect;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceCapability;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceDelegate;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationDescriptionBluetooth;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationDescriptionFireWire;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationDescriptionMassStorage;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationDescriptionUSB;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationOptions;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationType;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceLocationTypeMask;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceStatus;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceTransport;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceType;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICDeviceTypeMask;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICEnumerationChronologicalOrder;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICLocalizedStatusNotificationKey;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICSessionOptions;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICStatusCodeKey;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICStatusNotificationKey;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeBluetooth;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeExFAT;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeFireWire;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeMassStorage;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeProximity;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeTCPIP;
#[cfg(all(feature = "ICDevice", feature = "objc2"))]
pub use self::__ICDevice::ICTransportTypeUSB;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICAuthorizationStatus;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICAuthorizationStatusAuthorized;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICAuthorizationStatusDenied;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICAuthorizationStatusNotDetermined;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICAuthorizationStatusRestricted;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICDeviceBrowser;
#[cfg(all(feature = "ICDeviceBrowser", feature = "objc2"))]
pub use self::__ICDeviceBrowser::ICDeviceBrowserDelegate;
#[cfg(all(feature = "ICScannerBandData", feature = "objc2"))]
pub use self::__ICScannerBandData::ICScannerBandData;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypeCopy;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypeMail;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypePrint;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypeScan;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypeTransfer;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICButtonTypeWeb;
#[cfg(all(feature = "ICDevice", feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerDevice;
#[cfg(all(feature = "ICDevice", feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerDeviceDelegate;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerStatusRequestsOverviewScan;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerStatusWarmUpDone;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerStatusWarmingUp;
#[cfg(all(feature = "ICScannerDevice", feature = "objc2"))]
pub use self::__ICScannerDevice::ICScannerTransferMode;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerBitDepth;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerColorDataFormatType;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerDocumentType;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeature;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeatureBoolean;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeatureEnumeration;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeatureRange;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeatureTemplate;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFeatureType;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnit;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitDocumentFeeder;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitFlatbed;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitNegativeTransparency;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitPositiveTransparency;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitState;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitType;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerMeasurementUnit;
#[cfg(all(feature = "ICScannerFunctionalUnits", feature = "objc2"))]
pub use self::__ICScannerFunctionalUnits::ICScannerPixelDataType;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICEXIFOrientationType;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICErrorDomain;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICLegacyReturnCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnCodeOffset;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnConnectionErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnDownloadErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnMetadataErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnObjectErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnPTPDeviceErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICReturnThumbnailErrorCode;
#[cfg(all(feature = "ImageCaptureConstants", feature = "objc2"))]
pub use self::__ImageCaptureConstants::ICRunLoopMode;
